### ISSUE TITLE
Sometimes large albums are not fully loaded

### ISSUE THREAD

**Issue by hupfdule** [photoview/photoview#462] opened 2021-07-28 10:36 UTC
**Describe the bug**
Sometimes when opening a large album and scrolling to the end, the remaining images are not loaded.

**To Reproduce**
1. Open a a large album where not all images are loaded at once
2. Jump to the end of the album (either via key or scrollbar or …)
3. Wait until the remaining images are loaded
→ Sometimes they are not loaded. A reload of the whole page is necessary. Sometimes it works then, sometimes not.

**Expected behavior**
The remaining images should reliably load.

~~Also it should be visible that there are remaining images. Currently it is not yet visible whether the end of the album is reached (and more images are available) or not.~~
When the remaining images are being loaded a message "loading more media" is displayed at the bottom of the screen. This message is missing when the remaining images are not loaded.

**Your environment:**
 - Are you using Docker?: yes
 - Browser: Opera
 - Version: 2.3.5

**Additional context**
The system always loads a (to me unknown) amount of images and displays placeholders for the thumbnails. The _content_ of the thumbnails are then lazily loaded correctly. But if the user reaches the end of the page new _placeholders_ need to be created for the remaining images. These do not appear. The thumbnails for the displayed placeholders are always loaded correctly.

**Comment by viktorstrate** [comment] 2021-07-28 14:05
Duplicate of #302

**Closed by viktorstrate** 2021-07-28 14:05 UTC
Labels: bug
