### ISSUE TITLE
album open tip mysql error

### ISSUE THREAD

**Issue by lijianxiong** [photoview/photoview#815] opened 2023-03-08 10:24 UTC
**Describe the bug**
album open tip mysql error

**Screenshots**
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/4301287/223687660-f8e6e020-0949-4834-9f9f-4751beb113d1.png">

**Your environment:**
<img width="599" alt="image" src="https://user-images.githubusercontent.com/4301287/223687821-b44630e9-b468-4428-8e54-6f3d130b6be2.png">

 - Are you using Docker? [yes / no]
 - yes
 - Database [e.g. mariadb 10.5]
 - mysql 5.7.34
 - chrome
 - Version [e.g. 2.0.0]
 - 2.3.13 (446ef9a4)

**Additional context**
a@199508.com

**Comment by kkovaletp** [comment] 2024-05-05 16:05
@lijianxiong, thanks for the bug report. Is this bug still relevant for you? 
If you still have a system, where it can be reproduced, can you please export (and anonymize) your albums table from the DB and send us? Or at least take a readable screenshot of the result of `select * from albums;`?

It looks like the DB is corrupted somehow. This must be some configuration issue, as if this is a functional bug, we should get a lot of similar issues reported...

If there will be no response soon, it makes sense to close this issue as not planned, so in the case if it is reproduced in the future, a new issue with more details should be submitted.

**Comment by viktorstrate** [comment] 2024-05-07 05:37
It might be that the database version does not support recursive queries?

**Comment by kkovaletp** [comment] 2024-06-06 06:22
Closing the issue for now. If there are some useful details, it might be reopened in the future.

**Closed by kkovaletp** 2024-06-06 06:22 UTC
Labels: bug, needs information, pending response
