### ISSUE TITLE
memory usage - docker image of photoview

### ISSUE THREAD

**Issue by 1mfaasj** [photoview/photoview#772] opened 2022-11-09 08:17 UTC
I love photoview and use the Docker variant, only a pity that it takes up a lot of memory.
maybe something can be done about that?

I've loaded all my photos into it and am using 16 percent of the 8 GB at the moment, compared to other docker images I have running, that's a lot.

thanks in advance

**Comment by Revorge** [comment] 2022-11-11 11:24
That sounds weirdly high. How many photos are we talking? My library is about 300gb of photos and the container hovers around 100mb memory usage.

**Comment by kkovaletp** [comment] 2024-05-09 08:21
@1mfaasj, I cannot reproduce this issue as well. On my system, it uses 159 MB of RAM.
I'll close this issue. If this is still an issue for you, please open a new issue with a detailed description of your setup, and attach logs from `photoview` service, including container start and at least 1 complete scanner job. Also, please share your compose file.

**Closed by kkovaletp** 2024-05-09 08:21 UTC
Labels: bug
