### ISSUE TITLE
Merge Faces dialog broken

### ISSUE THREAD

**Issue by josh2112** [photoview/photoview#762] opened 2022-10-17 20:59 UTC
**Describe the bug**
The Merge Faces dialog seems to be broken in multiple ways:
 - It lists the other faces, and when you click on a face the name is bolded, but nothing ever seems to get selected (or there's no indication anyway). I would expect something like the list cell to change color, to be outlined, etc. You can narrow the list down to 1 face using the search feature, but there's still no indication that you're actually selecting the one face. The error message (`WHERE conditions required`) also makes me think a target face is not actually getting selected.
 - Clicking the Merge button results in the following error notification:
```Something went wrong
Server error: WHERE conditions required at (combineFaceGroups)
```

**To Reproduce**
1. Set up a gallery where at least 2 faces are found
2. Click People, then click on one of the faces
3. Click Merge Face
4. In the dialog, click on the other face (or at least try)
5. Click Merge

**Expected behavior**
The dialog should close and the original face and selected face should be merged into a new face

**Screenshots**
![image](https://user-images.githubusercontent.com/739972/196281487-036db582-f3c1-4261-9450-42ada6cefd65.png)

**Your environment:**
Docker with Mariadb/alpine on Raspberry Pi 3. Browser is Chrome. Not sure how to find the version of photoview in a docker image? It's whatever 'latest' docker pulled down today.

**Comment by korikori** [comment] 2022-10-24 11:14
Just got the same error while merging:
Server error: WHERE conditions required at (combineFaceGroups)

However, the photo was merged with the face.

**Comment by usma0118** [comment] 2023-04-03 12:28
facing same issue.

**Comment by roldengarm** [comment] 2023-05-16 08:43
I'm running into the same issue. The UI doesn't update, the dev console shows an error, but it seems to have updated it once I refresh.

**Comment by kkovaletp** [comment] 2024-05-09 09:13
Cannot reproduce the issue on the master docker image. Faces are merged successfully with no error and without refresh. Closing as completed.
If this issue is still reproducible on the master code, please submit a new issue with a detailed description of your setup and attach the Photoview logs at the time of the issue being reproduced

**Closed by kkovaletp** 2024-05-09 09:13 UTC
Labels: bug
