### ISSUE TITLE
Sorting of subalbums doesn't work

### ISSUE THREAD

**Issue by hupfdule** [photoview/photoview#461] opened 2021-07-28 09:49 UTC
**Describe the bug**
Changing the sort direction in an album with (only?) subalbums has no effect.

**To Reproduce**
- Open an album that contains multiple subalbums.
- Change the sort direction
- The order of the subalbums is not reversed

**Expected behavior**
- The sort order should be reversed each time the button for changing the sort direction is switched.

**Your environment:**

 - Are you using Docker?: yes
 - Browser: Opera
 - Version: 2.3.5

**Additional context**
I don't know whether the sort _type_ (by date, by title, etc.) is also not applied as the correspond in my case.

**Comment by viktorstrate** [comment] 2021-07-28 21:17
Duplicate of #366

**Closed** 2021-07-28 21:17 UTC
Labels: bug
