### ISSUE TITLE
Cannot "extend" a day to see the pictures containing it

### ISSUE THREAD

**Issue by ced455** [photoview/photoview#257] opened 2021-03-19 17:39 UTC
**Describe the bug**
When trying to "extend" a day to see al the pictures inside I get redirected to /album/1 and so can't see the pictures of that precise day

**To Reproduce**
1. go to /photos
2. Click on "+number" to see the picture taken that day
3. enjoy

**Expected behavior**
Being able to see the pictures of that day

**Screenshots**
![image](https://user-images.githubusercontent.com/26870023/111821247-537ed080-88da-11eb-8add-8782766f1c68.png)

**Your environment:**
Docker Latest Release 2.2.1
mariadb

**Comment by viktorstrate** [comment] 2021-03-19 18:06
I think this is a duplicate of #230, if you don't think so let me know and I'll reopen this issue :)

**Closed by viktorstrate** 2021-03-19 18:06 UTC
Labels: bug
