### ISSUE TITLE
Show GPS metadata for video files

### ISSUE THREAD

**Issue by dasKeks28** [photoview/photoview#894] opened 2023-10-01 19:15 UTC
Since video files can also store GPS coordinates, it would be great if those were also recognized by Photoview, including showing videos on the map.

**Comment by kkovaletp** [comment] 2023-10-01 20:06
It could be done by the command `exiftool -location:all input.mp4`, which will extract GPS data and convert it to human readable format, or by `ffmpeg -i input.mp4 -f ffmetadata -` - which will output raw metadata of the video and then we need to parse it to find the location.

Taking into account that the geolocation could be stored in different formats, the 2nd command gives more flexibility.

**Comment by kkovaletp** [comment] 2024-06-04 13:48
I just double-checked this on my testing instance and see the GPS data for videos in the DB, so the issue is not about extracting the data by scanner job from source files, but to display those videos in UI in the same way as photos.

**Comment by kkovaletp** [comment] 2024-10-19 09:00
I've submitted the #1093 with a more generic description, so I'm closing this issue as a duplicate with the intention of handling this case in the scope of that issue

**Closed by kkovaletp** 2024-10-19 09:00 UTC
Labels: help wanted, good first issue, feature, UI
