### ISSUE TITLE
Timeline View changes on refresh

### ISSUE THREAD

**Issue by phantomdez** [photoview/photoview#402] opened 2021-06-15 01:06 UTC
**Describe the bug**
When I am on the Photos Tab [Timeline view if I understand correctly]  the photos shown aren't the most recent in my library.  If I refresh the page the most recent photos [at the top of the page] changes.   Order of photos doesn't seem consistent with the timeline I took the pictures.  I cannot reproduce this on the demo.

**To Reproduce**
1. Go to Photos Tab
2. Already the photos aren't in chronilogical order
3. Hit F5 or Refresh the page.
4. Pictures change.

**Expected behavior**
I expect the pictures to be in chronilogical order and I don't expect them to change when I refresh the page.

**Screenshots**
Initial Page
![Screenshot 1](https://user-images.githubusercontent.com/56058726/121976959-e781fc00-cd52-11eb-9766-1fdf54ac6336.png)
After Refresh
![Screenshot 2](https://user-images.githubusercontent.com/56058726/121976963-e9e45600-cd52-11eb-89bb-c68c5b1e294a.png)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? yes
 - Database mariadb 10.5 as per the default Docker-compose config
 - Browser: Attempted with both Chrome and Firefox.  
Chrome: Version 91.0.4472.77 (Official Build) (64-bit)
Firefox: 89.0 64-bit

**Photoview Version**
Release Version
2.3.4 (90963f2f)
Build date
2021-05-27T09:47:02Z

**Additional context**
I am not sure if this has to do with how my photos are sorted as the same photos seem to cycle in the refreshed page.  My photos are sorted in folders as so:

Photos
|-->Year [Subfolder of Root Dir]
------|---->Month [Subfolder of Year]

I am not sure if the program is pulling EXIF data for the data or by the filename/folder structure but it seems it might conflict.  My second screenshot you can see the date is June 10th, 2021 but the photo is labeled in a folder 2013.

**Comment by viktorstrate** [comment] 2021-06-15 09:57
I think what is happening here is that

1. Photoview is not able to recognise the date of an image based on its path (yet).
And the date is not encoded in the EXIF information, theirefore the import date is used as a fallback value.

2. When the timeline is sorted, only the discrete day is used, which means that the database query doesn't differentiate between two images taken in the same day, this could easily be fixed by sorting on the timestamp as well.
This results in the database returning different orders each time.

Although the second problem could quickly be fixed it wouldn't solve the real problem (problem 1), which would require a more clever method for determining the date of an image where it isn't directly encoded in the metadata. This would probably not be a huge challenge to implement but it would require a well thoughout set of rules for determining the date based on the filepath, maybe someone has thought about this problem before.

**Comment by phantomdez** [comment] 2021-06-15 14:33
How does Photoview determine date?  There is data in EXIF for date that the photo was taken so wouldn't this be used?  I checked my files and they do have dates listed in the EXIF Data.  So I am not clear on your statement for problem 1.  I did copy this set of images from the original in testing the application as I wanted to get a feel for it so I am not sure if the filesystem timestamps correlate correctly as they are techincally new files on the system I have them on.  If that is how files dates are determined then that would indicate the experience I see based on your information on number 2.  However if dates are pulled from file timestamps and not EXIF data then my sort will always be off.

**Comment by phantomdez** [comment] 2021-06-15 14:48
Looks like I have some older images with DateTime Field filled but DateTimeOriginal field empty.  This is causing havoc on the sorting and confused me when I searched the EXIF data.  Not sure if this was due to an older version of EXIF standard or what but my problem seems to stem from some files missing the DateTimeOriginal field missing data.  As such Item 2 takes over as the import date is kept as the date taken and hence the sorting refreshes differently instead of based on time taken if I understood you correctly.    

Item 1 is my issue, but Item 2 I am not sure if this is the intended usage of how images are sorted and you may want to adjust.

**Comment by viktorstrate** [comment] 2021-06-15 19:13
Using `DateTime` if `DateTimeOriginal` is empty would be quite easy to implement. I could imagine that it's common for some cameras to store the `DateTime` but not the `DateTimeOriginal`.

**Comment by phantomdez** [comment] 2021-06-15 19:47
I am only noticing a few files from 2013 that was taken with an old phone camera that have this issue.  I think it would be a good idea for those that have images from older collections.  For now I updated the EXIF tag on my problematic photos.

I did also notice that Videos files aren't getting tagged by metadata date and rather by file creation time.  Is this by design? or is this a yet to be implemented feature?

**Comment by viktorstrate** [comment] 2021-06-17 10:19
Quickly looking at the code I think this was never properly implemented, videos are scanned for meta info but the date is never actually saved in the database

**Comment by phantomdez** [comment] 2021-09-15 18:26
Not sure where but I think this has been resolved.  Seems the videos where my primary issue with sorting.  I updated my test system today and I am seeing that videos are sorting into their proper folders now.  Seems to have been fixed with something else as I still see this open.  

Thanks Really liking this app.

**Comment by viktorstrate** [comment] 2021-09-15 18:38
Okay that's good to hear. I'll close this issue then, and if the problem is not entirely fixed, it's probably better to open a new issue instead.

Thank you for the update :)

**Closed by viktorstrate** 2021-09-15 18:38 UTC
Labels: bug
