### ISSUE TITLE
Remove people/face

### ISSUE THREAD

**Issue by paaland** [photoview/photoview#407] opened 2021-06-23 08:31 UTC
**Is your feature request related to a problem? Please describe.**
Several 1000s of photos got identified with the wrong person. I cannot to the move face function per image. 

**Describe the solution you'd like**
I'd like to remove the whole face and have all the images rescanned.

**Describe alternatives you've considered**
I did try and remove all the images from face_group table, but they are not scanned again. Any way to force the face scanning other than having to reset the whole database?

**Comment by viktorstrate** [comment] 2021-06-23 14:01
Duplicate of #269

**Closed by viktorstrate** 2021-06-23 14:01 UTC
