### ISSUE TITLE
Make EXIF and XMP data searchable

### ISSUE THREAD

**Issue by nstetter** [photoview/photoview#492] opened 2021-08-31 19:47 UTC
I would love to be able to search through Metadata (EXIF and XMP) to be able to find files by camera model, additional tags etc..

As far as I have seen from the RAEDME and  GH issues, as well as experimenting with photoview, this does not seem to be possible yet.

Thanks for putting in the hard work of working on this awesome project!

**Comment by viktorstrate** [comment] 2021-08-31 20:12
Thank you :) Is this a duplicate of #94?

**Comment by nstetter** [comment] 2021-08-31 20:17
Indeed it is a duplicate, sorry.

**Comment by viktorstrate** [comment] 2021-08-31 20:26
No problem :)

**Closed by viktorstrate** 2021-08-31 20:26 UTC
Labels: duplicate
