### ISSUE TITLE
Update libheif to fix issues with heif/heic photos taken in iOS 18

### ISSUE THREAD

**Issue by tobire** [photoview/photoview#1062] opened 2024-09-25 11:46 UTC
**Describe the bug**
libheif has problems with parsing photos taken in iOS 18.
It has been fixed in v1.18.0, as stated in this issue: https://github.com/strukturag/libheif/issues/1190

**To Reproduce**
Try to scan a .HEIC file that was created in iOS 18.
Example: https://www.dropbox.com/scl/fi/zv78otopss4hdhko2iy2w/IMG_0928.HEIC?rlkey=llqr6erkwbccse94iokklu22t&st=1rdf0i3h&dl=0

**Expected behavior**
The file gets scanned correctly

**Actual behavior**
ERROR: image decoding: failed to decode HEIF image (/photos/iPhone/IMG_0928.HEIC): Error while loading plugin: No decoding plugin installed for this compression format

**Comment by kkovaletp** [comment] 2024-09-25 11:55
@tobire, thanks for the report, however, the version of the lib is already up-2-date in `master`: https://github.com/photoview/photoview/blob/a1263feac4e0c7d8f605c38e5b4634983d3b4233/api/go.mod#L23
Please try the image with `master` tag and let us know whether it works for you.
Meanwhile, closing the issue as completed

**Comment by tobire** [comment] 2024-09-25 16:44
Thanks for the info. I didn't notice this, but I was already using the latest master tag, so this issue still persists, even though it seems that the correct version of libheif is used.

**Comment by kkovaletp** [comment] 2024-09-25 18:33
@tobire, please try to run `docker compose pull` - there is a chance that you use not the latest available image.
Also, please run `docker compose exec photoview bash -c "ls -lah /usr/local/lib/ |grep libheif"`
The result should be like:
```bash
lrwxrwxrwx 1 root root   12 Sep 17 16:08 libheif.so -> libheif.so.1
lrwxrwxrwx 1 root root   17 Sep 17 16:08 libheif.so.1 -> libheif.so.1.18.2
-rw-r--r-- 1 root root 1.3M Sep 17 16:08 libheif.so.1.18.2
```

If the `pull` doesn't pull a new image and the issue and the result doesn't show the `libheif.so.1.18.2`, please check your version in the UI on the Settings page: the latest `master` should have the `([a1263fea](https://github.com/photoview/photoview/commit/a1263feac4e0c7d8f605c38e5b4634983d3b4233))` version

**Comment by tobire** [comment] 2024-09-26 05:13
Seems like I'm on the latest image. I also purged all images and re-pulled them just to make sure, but the problem persists.

<img width="729" alt="grafik" src="https://github.com/user-attachments/assets/c63b1aaa-13bc-4e99-b57d-90f07954ecaf">

<img width="310" alt="grafik" src="https://github.com/user-attachments/assets/0e0fa65b-a3e0-498f-a33c-8acc5cd306fa">

**Comment by kkovaletp** [comment] 2024-09-26 06:54
@tobire, thanks a lot for your verification and confirmation! I don't have an iOS 18 device. Can you please share with us an example of a file, triggering the error? Please ZIP it without a password and attach here - in this way, we can be sure that GitHub doesn't change the file.

It looks like the lib is not used or not accessible by the product. I'm reopening the issue because of this. @googollee, could you please take a look at it as a priority, when you're back?

**Comment by tobire** [comment] 2024-09-26 07:04
Sure, here's an example: [heic-example.zip](https://github.com/user-attachments/files/17144283/heic-example.zip)

If you need anything to reproduce, just let me know.

**Comment by kkovaletp** [comment] 2024-09-26 10:50
Thanks, I've reproduced the issue. The full error message is:
```
Error scanning media for album (3) file (/photos/main/IMG_0928-iPhone-15.HEIC): process media database transaction: process media (/photos/main/IMG_0928-iPhone-15.HEIC): creating high-res cached image: image decoding: failed to decode HEIF image (/photos/main/IMG_0928-iPhone-15.HEIC): Error while loading plugin: No decoding plugin installed for this compression format 
```

**Comment by googollee** [comment] 2024-09-30 09:06
The problem is `No decoding plugin installed for this compression format`. I'll check the file and see which format it is and update the libheif dependency.

**Comment by kkovaletp** [comment] 2024-09-30 09:19
@googollee, if there are external plugins for the lib, please investigate which other plugins make sense to add to our project.
However, strategically, I'd go from processing non-RAW images by our own code (using libs) to shifting all the image processing to the external workers (ImageMagick, EXIFtool), as those tools are specially designed for this and maintained better (#996). So, if adding plugins requires noticeable efforts, let's save that time and fix this issue by the #996 implementation sooner.

**Comment by googollee** [comment] 2024-09-30 10:01
I did some tests with the example image.

In Debian bookworm with official Imagemagick 6.8:

```
$ identify --verbose IMG_0928.HEIC 
identify-im6.q16: unable to open image `--verbose': No such file or directory @ error/blob.c/OpenBlob/2924.
identify-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/580.
```

In Debian bookworm with Imagemagick 7 from `dpokidov/imagemagick:latest-bookworm`:

```
$ magick identify --verbose ./IMG_0928.HEIC 
Assertion failure at kmp_affinity.cpp(536): core_level != -1.
OMP: Error #13: Assertion failure at kmp_affinity.cpp(536).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.
Aborted (core dumped)
```

In the latest ChromeOS:
![image](https://github.com/user-attachments/assets/919d4b95-6e3c-41bb-8e0d-54154b7973f7)

From exif, this image was shooted by iPhone 15:

```
$ exiftool IMG_0928.HEIC 
ExifTool Version Number         : 12.57
File Name                       : IMG_0928.HEIC
Directory                       : .
File Size                       : 1221 kB
File Modification Date/Time     : 2024:09:30 11:41:59+02:00
File Access Date/Time           : 2024:09:30 11:42:18+02:00
File Inode Change Date/Time     : 2024:09:30 11:41:59+02:00
File Permissions                : -rw-r--r--
File Type                       : HEIC
File Type Extension             : heic
MIME Type                       : image/heic
Major Brand                     : High Efficiency Image Format HEVC still image (.HEIC)
Minor Version                   : 0.0.0
Compatible Brands               : mif1, tmap, MiHE, miaf, MiHB, heic
...
Host Computer                   : iPhone 15
...
Field Of View                   : 69.4 deg
Focal Length                    : 6.0 mm (35 mm equivalent: 26.0 mm)
Hyperfocal Distance             : 3.22 m
Light Value                     : 2.2
Lens ID                         : iPhone 15 back dual wide camera 5.96mm f/1.6
```

What `libheif` dependencies are missing in our dependencies image:

- [KVAZAAR](https://tracker.debian.org/pkg/kvazaar), not exist in stable.
- [OpenJPEG](https://tracker.debian.org/pkg/openjpeg), not exist in stable.
- [OPENJPH](https://tracker.debian.org/pkg/openjph), the version is not the latest in stable and can't be compiled with the latest `libheif`. Currently it's [0.17.0](https://github.com/aous72/OpenJPH/releases).
- [LIBSHARPYUV](https://packages.debian.org/unstable/libsharpyuv-dev), it's built from [webp](https://tracker.debian.org/pkg/libwebp) `1.4.0` and not exist in stable.

I guess it requires one of packages above and we need to build it ourselve.

**Comment by googollee** [comment] 2024-09-30 10:13
With `islandora/imagemagick:main`:

```
$ ldd libheif.so
        /lib/ld-musl-x86_64.so.1 (0x7f36a36b2000)
        libx265.so.209 => /usr/lib/libx265.so.209 (0x7f36a235a000)
        libde265.so.0 => /usr/lib/libde265.so.0 (0x7f36a22e6000)
        libaom.so.3 => /usr/lib/libaom.so.3 (0x7f36a1b65000)
        libsharpyuv.so.0 => /usr/lib/libsharpyuv.so.0 (0x7f36a1b5d000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f36a18c4000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f36a18a0000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f36a36b2000)
        libnuma.so.1 => /usr/lib/libnuma.so.1 (0x7f36a1894000)
$ magick identify -list format 
   Format  Module    Mode  Description
-------------------------------------------------------------------------------
...
     HEIC  HEIC      rw+   High Efficiency Image Format (1.17.6)
     HEIF  HEIC      rw+   High Efficiency Image Format (1.17.6)
...
$ magick identify IMG_0928.HEIC 
identify: Invalid input: Unspecified: Too many auxiliary image references (2.0) `IMG_0928.HEIC' @ error/heic.c/IsHEIFSuccess/141.
```

**Comment by googollee** [comment] 2024-09-30 10:28
More checking with self-building `libheif`:

```
root@a665384a60e6:/app# heif-info IMG_0928.HEIC 
MIME type: image/heic
main brand: heic
compatible brands: mif1, tmap, MiHE, miaf, MiHB, heic

image: 3024x4032 (id=49), primary
  colorspace: YCbCr, 4:2:0
  bit depth: 8
  color profile: prof
  alpha channel: no 
  depth channel: no
metadata:
  Exif: 2582 bytes
  XMP: 2541 bytes
transformations:
  angle (ccw): 270
region annotations:
  none
properties:
```

And I notice that:

```
# make install
...
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-x265.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-libde265.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-dav1d.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-aomdec.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-aomenc.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-svtenc.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-rav1e.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-jpegdec.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-jpegenc.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-ffmpegdec.so
-- Up-to-date: /usr/local/lib/libheif.so.1.18.2
-- Up-to-date: /usr/local/lib/libheif.so.1
-- Up-to-date: /usr/local/lib/libheif.so
...
```

Maybe we are missing those plugins.

**Comment by kkovaletp** [comment] 2024-09-30 10:44
I also tried to convert the file inside our `master` image using ImageMagick:
```
photoview@photoview:/photos/main$ magick ./IMG_0928-iPhone-15.HEIC -quality 90 /home/photoview/media-cache/tmp.jpg
magick: Error while loading plugin: No decoding plugin installed for this compression format (11.6003) `./IMG_0928-iPhone-15.HEIC' @ error/heic.c/IsHEIFSuccess/141.
```
So, it looks like we have missing plugins for ImageMagick as well

**Comment by googollee** [comment] 2024-09-30 10:46
Looks like with those plugins, `magick` works well:

```
$ ls /usr/local/lib/
libheif-aomdec.so     libheif-jpegdec.so   libheif-svtenc.so  libheif.so.1.18.2        libraw_r.so
libheif-aomenc.so     libheif-jpegenc.so   libheif-x265.so    libpixbufloader-heif.so  libraw_r.so.23
libheif-dav1d.so      libheif-libde265.so  libheif.so         libraw_r.a               libraw_r.so.23.0.0
libheif-ffmpegdec.so  libheif-rav1e.so     libheif.so.1       libraw_r.la
$ magick identify IMG_0928.HEIC 
IMG_0928.HEIC HEIC 3024x4032 3024x4032+0+0 8-bit sRGB 1.16398MiB 0.010u 0:00.002
```

I'll create a PR and a test image.

**Comment by kkovaletp** [comment] 2024-09-30 10:57
> magick identify IMG_0928.HEIC

yes, `identify` command works fine, but `convert` doesn't. For us, the `convert` is much more important. But we could add missing plugins for ImageMagick in the scope of #996

**Comment by googollee** [comment] 2024-09-30 11:23
@tobire could you check if the problem still exists with `ghcr.io/googollee/photoview:ios-18-heif-1062` image? I'll check it later today.

**Comment by googollee** [comment] 2024-09-30 15:52
Now `magick` works well with the image `ghcr.io/googollee/photoview:ios-18-heif-1062`:

```
# magick IMG_0928.HEIC img.jpg
# ls
IMG_0928.HEIC  code  img.jpg
```

**Comment by googollee** [comment] 2024-09-30 17:52
![image](https://github.com/user-attachments/assets/9729f909-14aa-41af-af7d-401b06d57019)

libheif works well on my local test env.

**Closed** 2024-09-30 17:53 UTC
Labels: bug, scanner, dependencies, docker, high priority

**Comment by googollee** [comment] 2024-09-30 19:25
@tobire This issue has been fixed with the latest image. Please check if it works.

**Comment by kkovaletp** [comment] 2024-09-30 19:26
> with the latest image

means `master` tag)

**Comment by tobire** [comment] 2024-10-01 05:23
Works as expected now!
Thanks for your work @googollee & @kkovaletp :)
