### ISSUE TITLE
large folder no album

### ISSUE THREAD

**Issue by tausday** [photoview/photoview#872] opened 2023-08-08 20:55 UTC
Hello,

i have on folder and in this folder are  ~4500 pictures and 40GBs.
in this folder are also 3 small folder with pictures.

I can the pictures in the small folder with 10 pictures.
If I go back to the main folder in album view i just see the folder.

In Timeline in can see the pictures with a white freespace.

I have install Photoview twice and clear from docker without modifications

All other small folders with <100pictures works very well and fast.

i have wait many or and on the bottom the scan was finished.

Can i make a debug or something else to get an better support from me?

Thanks

i have added three pictures album, filesystem and timeline view.

on the bottom you can see photoview finds files but i does not show it

<a href="https://ibb.co/hgMD0r3"><img src="https://i.ibb.co/7Sz2hBs/album.png" alt="album" border="0"></a>
<a href="https://ibb.co/d0m5NB1"><img src="https://i.ibb.co/5WKRQTt/folder.png" alt="folder" border="0"></a>
<a href="https://ibb.co/0stSXLc"><img src="https://i.ibb.co/RjymSK9/timeline.png" alt="timeline" border="0"></a>

**Comment by tausday** [comment] 2023-08-09 10:09
hello,

i have found out, that the problem is a video, but i don't can find out which..
I have watched into compose log, but there are just the boot sequents.
can i increase the debug lvl?

**Comment by tausday** [comment] 2023-08-19 11:29
i have the same problem in a screenshots folders where are only png..

**Comment by kkovaletp** [comment] 2024-04-29 15:54
Most probably your issue was caused by the #729, so closing this as a duplicate. Feel free to submit a new issue if it still reproduces on the recent image from `master` branch (with the `master` tag)

**Closed by kkovaletp** 2024-04-29 15:54 UTC
Labels: bug, duplicate
