### ISSUE TITLE
Error getting version of darktable: exit status 1

### ISSUE THREAD

**Issue by myuseraccount** [photoview/photoview#819] opened 2023-03-15 19:10 UTC
**Describe the bug**
My raw files (Canon .CR2) don't get processed.  In the logs, when I was first starting up my server (and permissions were wonky), I have a few entries that read like this:
```
photoview[1953507]: 2023/03/10 16:38:48 Error getting version of darktable: exit status 1
```
**To Reproduce**
At this point, this doesn't appear in the logs anymore, so I don't know if it is even trying to detect raw files.  My folders that contain raw files also contain JPEGs, and those are getting processed.

**Expected behavior**
I would think it would at least have some kind of log entry indicating it detects, or fails to detect, darktable, or that it detects raw files in my folders and tries to process them.

**Your environment:**
 - Are you using Docker? [no]
 - OS [Ubuntu 22.04]
 - Startup [systemd]
 - Database [MySQL 8.0]
 - Darktable [3.8.1]
 - Browser [various, mostly Firefox, Windows and Linux]
 - Version [unknown]

I installed from the manual install instructions, but with the command example of `git clone`, not the part above it that says to download and unzip a release.  This was less than a week ago.

Under Settings in the UI, it says this:
### Release Version
undefined ()
### Build date
undefined

**Additional context**
I installed Darktable with apt.  It works when I run `darktable-cli --version` as myself.  The instructions say to make sure darktable-cli is in the `$PATH` but how do I define that for the photoview user that has no shell?  I tried putting `PATH=$PATH:/usr/bin` in the `/etc/photoview.env` file but it didn't make any difference.

**Comment by myuseraccount** [comment] 2023-03-21 23:00
I thought I saw another issue that mentioned someone not getting raw files scanned in the same folder as JPGs, but I can't find it.  It's possible it's related to [this one](https://github.com/photoview/photoview/issues/391) but I'm not getting any errors in the logs related to raw files.

**Comment by kkovaletp** [comment] 2024-05-03 19:07
@myuseraccount, as this issue was submitted a year ago with no recent comments, I hope that you found a way to solve it, but I'll provide the solution here just for history.

If I got the case correctly, the issue was caused by inability of Photoview to locate the `darktable-cli` executable, as it was not in the $PATH of the user, under which it was running.
You've mentioned that you configured Photoview to run on Ubuntu as a systems service, so here is the solution for this setup:
- assuming that you have a user created and configured correctly, as well as the Darktable installed and in working state
- You need to create the `photoview.service` file with the content, similar to:
```
[Unit]
Description=Photoview web server
After=network.target

[Service]
User=myappuser
Group=myappgroup
Environment="PATH=/darktable/path:%p"
ExecStart=/path/to/photoview

[Install]
WantedBy=default.target
```
The most important here is the `Environment="PATH=/darktable/path:%p"` line, where you can define the path to the `darktable-cli` and optionally to some other executables, separated by the `:`, and add the `%p` at the end, which should be expanded to the content of the default $PATH variable for the user to ensure that all system executables are still accessible.

With this I'll close the issue. Feel free to open a new one in the case, you need some more assistance

**Closed by kkovaletp** 2024-05-03 19:07 UTC
Labels: bug

**Comment by myuseraccount** [comment] 2024-05-09 16:04
Thanks @kkovaletp !  I'll try that when I get a chance, much appreciated.
