### ISSUE TITLE
Scanning of folder with mix of jpg and heic only scans jpg

### ISSUE THREAD

**Issue by suncore** [photoview/photoview#748] opened 2022-09-12 08:38 UTC
**Describe the bug**
I'm trying to scan a folder that have a mix of jpg and heic files. Only the jpg files are scanned.

**To Reproduce**
Create folder with mix of jpg and heic, try to scan. Only jpg is scanned.

**Expected behavior**
All files scanned

**Screenshots**
NA

**Your environment:**
Ubuntu. Photoview in docker compose as described

 - Are you using Docker? [yes / no]
yes
 - Database [e.g. mariadb 10.5]
mariadb (installed yesterday, not sure about version)
chrome
 - Version [e.g. 2.0.0]
latest

**Additional context**

**Comment by vijfhoek** [comment] 2022-10-08 18:36
Are you getting errors in your terminal? This sounds pretty similar to #740

**Comment by kkovaletp** [comment] 2024-05-11 12:10
I cannot reproduce this issue using the current master code:
My phone saves photos in HEIC files, so I put several HEIC photos in my testing folder with JPG and other types of files, then started the scan job from the Settings page: all files were scanned as expected, including HEIC ones.
So, it looks like the issue is fixed somehow now and I'll close it as completed.

If you still can reproduce it on the current master code / docker image, please open a new issue with detailed steps to reproduce, and please, share an example of the image, skipped by the job. Also, please share the Photoview job execution log of the scan job, where the issue was reproduced.
Please note that Photoview reports errors and skips corrupted media (even if the corruption is small and other viewers auto-fix it, so you might think that it is fine): #892.

**Closed by kkovaletp** 2024-05-11 12:10 UTC
Labels: bug
