### ISSUE TITLE
ERROR: Error detecting faces in image (/photos/photo/IMG_20210214_135111.jpg): thumbnail url is missing

### ISSUE THREAD

**Issue by beermedlar** [photoview/photoview#214] opened 2021-02-23 15:44 UTC
I am running photoview use viktorstrate/photoview:nightly by docker.
When I scanning the media. I get a lot of error logs.
Here are some of the logs.

```
2021/02/23 23:35:34 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:34 ERROR: Error detecting faces in image (/photos/photo/IMG20200620092818.jpg): thumbnail url is missing

2021/02/23 23:35:34 Broadcasting notification: Scanner error

2021/02/23 23:35:34 Processing photo: /photos/photo/IMG20200712195828.jpg

2021/02/23 23:35:34 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:34 ERROR: Error detecting faces in image (/photos/photo/IMG20200712195828.jpg): thumbnail url is missing

2021/02/23 23:35:34 Broadcasting notification: Scanner error

2021/02/23 23:35:34 Processing photo: /photos/photo/IMG_20200615_102815.jpg

2021/02/23 23:35:34 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:34 ERROR: Error detecting faces in image (/photos/photo/IMG_20200615_102815.jpg): thumbnail url is missing

2021/02/23 23:35:34 Broadcasting notification: Scanner error

2021/02/23 23:35:34 Processing photo: /photos/photo/IMG_20200615_195912.jpg

2021/02/23 23:35:34 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:34 ERROR: Error detecting faces in image (/photos/photo/IMG_20200615_195912.jpg): thumbnail url is missing

2021/02/23 23:35:34 Broadcasting notification: Scanner error

2021/02/23 23:35:34 Processing photo: /photos/photo/IMG_20200618_165327.jpg

2021/02/23 23:35:34 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:34 ERROR: Error detecting faces in image (/photos/photo/IMG_20200618_165327.jpg): thumbnail url is missing

2021/02/23 23:35:34 Broadcasting notification: Scanner error

2021/02/23 23:35:34 Processing photo: /photos/photo/IMG_20200620_092843.jpg

2021/02/23 23:35:35 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:35 ERROR: Error detecting faces in image (/photos/photo/IMG_20200620_092843.jpg): thumbnail url is missing

2021/02/23 23:35:35 Broadcasting notification: Scanner error

2021/02/23 23:35:35 Processing photo: /photos/photo/IMG_20200620_092938.jpg

2021/02/23 23:35:35 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:35 ERROR: Error detecting faces in image (/photos/photo/IMG_20200620_092938.jpg): thumbnail url is missing

2021/02/23 23:35:35 Broadcasting notification: Scanner error

2021/02/23 23:35:35 Processing photo: /photos/photo/IMG_20200620_093107.jpg

2021/02/23 23:35:35 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:35 ERROR: Error detecting faces in image (/photos/photo/IMG_20200620_093107.jpg): thumbnail url is missing

2021/02/23 23:35:35 Broadcasting notification: Scanner error

2021/02/23 23:35:35 Processing photo: /photos/photo/IMG_20200620_093439.jpg

2021/02/23 23:35:35 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:35 ERROR: Error detecting faces in image (/photos/photo/IMG_20200620_093439.jpg): thumbnail url is missing

2021/02/23 23:35:35 Broadcasting notification: Scanner error

2021/02/23 23:35:35 Processing photo: /photos/photo/IMG_20200620_103029.jpg

2021/02/23 23:35:35 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:35 ERROR: Error detecting faces in image (/photos/photo/IMG_20200620_103029.jpg): thumbnail url is missing

2021/02/23 23:35:35 Broadcasting notification: Scanner error

2021/02/23 23:35:35 Processing photo: /photos/photo/IMG_20200620_103126.jpg

2021/02/23 23:35:35 Broadcasting notification: Processing media for album 'photo'

2021/02/23 23:35:35 ERROR: Error detecting faces in image (/photos/photo/IMG_20200620_103126.jpg): thumbnail url is missing

2021/02/23 23:35:35 Broadcasting notification: Scanner error
```

**Comment by viktorstrate** [comment] 2021-02-25 20:52
Do you think you can provide steps for reproducing these errors?

**Comment by joesteffee** [comment] 2021-03-05 20:52
I'm also having this problem, running latest docker image. Importing a large-ish library from scratch about half the images return this error. Assuming it might be some kind of race condition where the thumbnail is scanned prior to it being generated?

**Comment by Shagon94** [comment] 2021-03-06 09:14
I've also ran this on my library, I think that the issue also occurs if a face is not in the picture, i.e. a picture of landscape; It might be classified as an error but it is an expected outcome, face detection cannot detect a face on a picture that doesn't have a person in it.

**Comment by FishOnTheGround** [comment] 2021-03-07 08:27
Also gpt this error during the scan proces. Running latest Photoview on docker and my database is the one from linuxserver/mariadb:alpine because the one suggested in the readme of Photoview does not support 32-bit arm, which I use.

**Comment by ced455** [comment] 2021-03-08 17:07
Hello.

I Got the same issue but it does not stop the app from working so it's fine :) , is there a way to force face detection now that my first batch of picture have been imported ?

**Comment by viktorstrate** [comment] 2021-03-08 19:02
Hi @ced455 that's good to hear. I will work on this issue as the first thing when I have the time.
There is no way to force a new face detection scan, other than removing the path in the settings and re-adding it again, but then it will have to regenerate the thumbnails as well, and favorites and shares are lost.

**Comment by FishOnTheGround** [comment] 2021-03-08 22:04
Maybe a little offtopic, but it would be nice to have an option to merge 2 discovered faces when it is the same person but recognised as 2 different people.

**Comment by viktorstrate** [comment] 2021-03-09 07:53
@FishOnTheGround You can do that by clicking on the gear icon next to the face label.
Please open a new issue or use the discussion if you have further questions to keep this thread on topic.

**Comment by viktorstrate** [comment] 2021-03-16 17:28
Should be fixed with 3ae9208, if anyone experience this again (using a build after this commit), please write a comment and I will reopen it.

**Comment by ced455** [comment] 2021-03-16 17:36
Thanks ! Using photo view via viktorstrate/photoview docker so will wait for release / build there :)

**Comment by viktorstrate** [comment] 2021-03-16 17:38
You're welcome, I will push a new release soon.

**Comment by ced455** [comment] 2021-03-16 17:56
Jumped on the edge version on docker and restarted from scratch :

![image](https://user-images.githubusercontent.com/26870023/111357111-e91f2380-8680-11eb-9e44-019588e9107a.png)

Do you need some more logs or me to raise a new ticket ?

**Comment by viktorstrate** [comment] 2021-03-16 20:30
I had not tested it yet. Thank you for doing so.

**Comment by viktorstrate** [comment] 2021-03-16 21:30
@ced455 I just pushed another fix. I narrowed it down to a quite peculiar bug regarding goroutines.
I tested it locally and it seemed to work. Would you mind testing it to verify?

**Comment by ced455** [comment] 2021-03-16 21:32
sure, as soon the build is available in docker hub ! :)

**Comment by viktorstrate** [comment] 2021-03-16 21:33
Awesome, thanks a lot!

**Comment by ced455** [comment] 2021-03-16 21:46
No errors, face are getting discovered !
Well Done !

**Comment by viktorstrate** [comment] 2021-03-16 22:02
Awesome 🎉 thank you for helping with the testing

**Closed by viktorstrate** 2021-03-16 22:02 UTC
Labels: bug, high priority
