### ISSUE TITLE
New photos not updating

### ISSUE THREAD

**Issue by Darkw00** [photoview/photoview#831] opened 2023-04-16 11:33 UTC
I had everything setup correctly with docker but now I have noticed that no new photos are updating/adding to the library. Only photo prior 24. .3. 23 are displayed and there are no new photos. The folder which is the library is still setup correctly and has new photos in it. 

Can anybody help me how should i approach to fix the issue.

**Comment by kkovaletp** [comment] 2024-05-03 18:32
@Darkw00 as the issue was submitted a year ago and not commented on since that, I'd assume that it is not relevant for you anymore.
From the description, it looks like this is a configuration issue, related to the scanner and \ or job schedule settings. You didn't provide the logs from Photoview and didn't describe your setup, so I can say nothing more.

With this, I'll close it for now. If the issue is still relevant to you, please submit the new one and provide a detailed description of the environment, configuration on the Settings page, and logs for the Photoview process (or from photoview container, depending on the setup type) for at least 2 job schedule intervals

**Closed by kkovaletp** 2024-05-03 18:32 UTC
