### ISSUE TITLE
Cannot scan photos, and permission error is raised.

### ISSUE THREAD

**Issue by vanillapod-ze** [photoview/photoview#695] opened 2022-05-08 16:15 UTC
**Describe the bug**
Images cannot be scanned, when clicked `settings/users/scan`, nothing changed until clicking `Scan all users`, it raised permission denied error.

> **Something went wrong**
> Server error: failed to add user for scanning (6): find albums for user (user_id: 6): read directory (/photos): open /photos: permission denied at (scanAll)

**To Reproduce**
1. vim `docker-compose.yml`, replace `- ./photos_path:/photos:ro` with`- ./photos:/photos`
2. move my photos into `./photos`
3. restart docker with `docker-compose down && docker-compose up -d`
4. visit the web site 
5. click `settings/users/scan` and `Scan all users` button

**Expected behavior**
Albums is empty but `./photo` is not. Permission denied error was raised, but user `photoview` do have `admin` permission.

**Screenshots**
Browser
![image](https://user-images.githubusercontent.com/48322394/167304219-1104ca78-8fdc-4e06-86f9-d7ba52606009.png)

Running `docker-compose logs`
![image](https://user-images.githubusercontent.com/48322394/167304684-265dfd28-efe1-44e5-a242-72583c9c2efc.png)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? [yes]
 - Database [mariadb 10.5]
 - Browser [firefox v100]
 - Version [2.0.0]

**Additional context**
I don't understand why, shouldn't I put my photos into `./photos` ? I tried to remove `:ro` flag, but found `/photos` is still Read-only by running `docker exec -it photoview_photoview_1 /bin/bash`.

There are some files in `./photos`
![image](https://user-images.githubusercontent.com/48322394/167304909-b06ecdaf-9939-4376-b547-8fec69f91e33.png)

But albums is empty
![image](https://user-images.githubusercontent.com/48322394/167305054-513ce184-1c37-4807-9afe-ee43a683d6f0.png)

**Comment by PengCheong** [comment] 2022-05-08 16:32
btw, I am running docker under Silverblue F36, and run a clean photoview, the auto-gen-folder photos_path is owned by `root` instead of current user, is it right?

```bash
[cp@fedora photoview]$ stat -c "%U %G"  photos_path/
root root
```

On my operations above, I have already change the folder's owner to my username before moving my photos into `photoview/photos`

**Comment by cloo** [comment] 2022-06-12 21:40
Same problem here. 
No docker, Yunohost installation, nextcloud folder.

**Comment by kkovaletp** [comment] 2024-06-06 16:43
@vanillapod-ze , thanks for your report. To me, it looks like an issue with file permissions on the host and some incompatibility with mounting to docker.

Anyway, we've done a big refactoring of the docker image and compose file. So, please try the config from the `master` branch and use the `photoview:master` image with it. I think that this issue should be fixed there.

Please let me know the results. If no response is provided soon, this issue will be closed as not planned, because it doesn't look like we still have this issue in the product.

**Comment by faptaincrunch** [comment] 2024-07-03 19:36
Same issue here using [Master branch. ](photoview:master)

**Comment by kkovaletp** [comment] 2024-07-04 04:24
@faptaincrunch, did you follow the instructions from the Readme: https://github.com/photoview/photoview#getting-started--setup-with-docker to configure the permissions of the volumes for the `photoview` image?
If yes, which exactly errors did you get?

**Comment by kkovaletp** [comment] 2024-09-22 08:20
Closing the issue as not planned, because it is caused by misconfiguration

**Closed by kkovaletp** 2024-09-22 08:20 UTC
Labels: bug, scanner, docker, needs information, pending response
