### ISSUE TITLE
Wrong timezone on docker

### ISSUE THREAD

**Issue by ouafnico** [photoview/photoview#556] opened 2021-10-04 11:48 UTC
**Describe the bug**
The timezone on the docker is not correct.
I think it's make wrong the use of dates on exif.

**To correct**

One of solution is to add this volume on photoview docker-compose :
```
      - /etc/localtime:/etc/localtime:ro
```

**Comment by viktorstrate** [comment] 2021-10-05 17:10
What is the problem? Where does this become apparent?
And is this a duplicate of #306?

**Comment by ouafnico** [comment] 2021-10-05 17:15
I though it was the source of the incorrect creation date of pictures shown on photoview. 
They all got +2h on te creation date, and my docker was 2h drifting because of the bad timezone.

But after the reset of database and full rescan all pictures, with a correct timezone on docker, I still got all my pictures with a wrong creation date.

**Comment by ouafnico** [comment] 2021-10-05 17:16
It may be the same as #306  indeed

**Comment by viktorstrate** [comment] 2021-10-05 17:55
Ok, I'll close this one then

**Closed by viktorstrate** 2021-10-05 17:55 UTC
Labels: bug
