### ISSUE TITLE
Database cleanup/Cache scan and rebuild

### ISSUE THREAD

**Issue by secco04** [photoview/photoview#1148] opened 2024-12-27 21:58 UTC
**Is your feature request related to a problem? Please describe.**
I got a huge Cache folder with dupliates of converted Videos. (and maybe also pics) 
I deleted them all but they seem to still exist in the DB creating errors in the logs. 

**Describe the solution you'd like**
I would like to clean up the orphaned db entry and/or rebuild the Cache 

**Additional context**
Log entry:

ERROR: after reprocessing video not found in cache: stat /app/cache/1025/79602/web_video_Dvd-7_mkv_W86KzNWp.mp4: no such file or directory

**Comment by kkovaletp** [comment] 2024-12-28 08:38
@secco04, thanks for your report.
How did you detect duplicates of videos in the cache? Photoview creates cached videos for originals in your media library.
If you remove or rename those originals, a subsequent scan will remove corresponding cached files and generate new ones for renamed and new originals, as it doesn't see a difference between these 2 cases.

So, you shouldn't manually remove anything from your cache folder. The error, you reported here, is caused by this invalid operation.

We have another issue with the request to optimize the scan job and better process updated files in the media library: #760. Please read it and add your comments if you think there is something, you can add there.

With this, I'm closing this issue as a duplicate.
You still can reply and if we discover new symptoms and clarify that this is not a duplicate, I'll reopen it back.

**Closed by kkovaletp** 2024-12-28 08:38 UTC
