### ISSUE TITLE
Delete function from web/app

### ISSUE THREAD

**Issue by scho0ck** [photoview/photoview#724] opened 2022-08-03 20:50 UTC
**Is your feature request related to a problem? Please describe.**
Hi there, love photoview but as I'm autouploading files from my phone there's a lot of junk as well I would love to have a delete button in photoview to delete files from the web or app (iOS)

**Describe the solution you'd like**
Add delete option to photoview

**Describe alternatives you've considered**
None

**Comment by viktorstrate** [comment] 2022-08-05 00:07
duplicate of #216

**Closed by viktorstrate** 2022-08-05 00:07 UTC
Labels: duplicate
