### ISSUE TITLE
Autodetect media types instead of declaring them in the `api/scanner/media_type/media_type.go`

### ISSUE THREAD

**Issue by kkovaletp** [photoview/photoview#996] opened 2024-07-12 15:55 UTC
**Is your feature request related to a problem? Please describe.**
Photoview skips and doesn't process source media files of certain types, even while media processing tools, used by Photoview, support those types.

**Describe the solution you'd like**
It would be great to find an automatic way of importing all known to be supported media types at Photoview build time, but until that we need to periodically update the `api/scanner/media_type/media_type.go` an add missing types manually.
Source for the supported types should be the tools' documentation:
- Darktable: https://docs.darktable.org/usermanual/4.6/en/overview/supported-file-formats/
- FFmpeg: https://ffmpeg.org/ffmpeg.html (looks like there is no list of supported formats, instead it declares support for all known video and audio formats, but this should be researched and confirmed additionally by a contributor)

**Describe alternatives you've considered**
Is it possible to simplify the workflow by somehow detecting whether a file is an image or a video without having a list of predefined formats or extensions? If yes, we can probably simply try to process every found image with Darktable and video - by ffmpeg. Or even without such a detection: simply try to process every found file by Darktable, and if an error is returned, try ffmpeg, if an error is returned again, then this is not a supported media (or not a media at all), so skip it.
This simplification has to be reviewed and researched, as it is based on assumptions and might be completely wrong or result in unexpected outcomes or performance degradation.

**Comment by kkovaletp** [comment] 2024-07-12 16:01
@jordy2254, @googollee, what do you think about the alternative solution, described in the issue? 
Does it or some similar approach make sense to implement?

Do you know about some way or tool to auto-detect the media type of a file (image, video, audio) to implement a smarter workflow? It would be great to switch to some sort of auto-detection from the dictionary-based approach, as with the current implementation we'll always miss some new formats and periodically have to add them to the dict manually...

**Comment by googollee** [comment] 2024-07-12 18:06
I agree on that it's not a good way to detect files based on the ext name. I know some ways to detect files.

`ffmpeg` provides `ffprobe` to show files metadata. If it parses the file, the command returns `0`, otherwise `1`. It supports both videos and photos, but not raw files.

`exiftool` could guess file's MIME Type based on the content. It works well with photos and raw files, but I don't know if it supports videos.

I guess `darktable` would provide a similar feature, but I can't find it in the manual. We could just run it to try to generate a cache file. If the generation fails, then it's a non-support file. It may be slower than the other two ways, but I think it's a good way as if we could convert a file to jpeg with `darktable`, we can say `photoview` supports that file. As that conversion runs in a queue, the speed is not a serious problem.

**Comment by googollee** [comment] 2024-07-12 19:59
I tried `darktable-cli`. It did return a different code if a file can't be converted to a jpg.

```sh
root@cca6396b85ac:/app/api# darktable-cli ./go.mod ./go.mod.jpg --core --conf plugins/imageio/format/jpeg/quality=90
430206151.1223 WARNING: either your user id or the effective user id are 0. are you running darktable as root?
error: can't open file ./go.mod
no images to export, aborting
root@cca6396b85ac:/app/api# echo $?
1

root@cca6396b85ac:/app/api# cp go.mod go.jpg
root@cca6396b85ac:/app/api# darktable-cli ./go.jpg ./go.mod.jpg --core --conf plugins/imageio/format/jpeg/quality=90
430206327.5525 WARNING: either your user id or the effective user id are 0. are you running darktable as root?
     3.8882 [rawspeed] (go.jpg) virtual std::unique_ptr<rawspeed::RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData*), line 97: No decoder found. Sorry.
     3.8884 [libraw_open] extensions whitelist: `cr3'
     3.8887 [qoi_open] no proper file header in ./go.jpg
Not a JPEG file: starts with 0x6d 0x6f
     3.9236 [dt_imageio_export_with_flags] mipmap allocation for `./go.mod.jpg' failed
     3.9242 [imageio_storage_disk] could not export to file: `./go.mod.jpg'!
root@cca6396b85ac:/app/api# echo $?
1

root@cca6396b85ac:/app/api# darktable-cli ./scanner/test_data/buttercup_close_summer_yellow.jpg butter.jpg --core --conf plugins/imageio/format/jpeg/quality=90
430206184.0158 WARNING: either your user id or the effective user id are 0. are you running darktable as root?
     5.0814 [export_job] exported to `butter.jpg'
root@cca6396b85ac:/app/api# echo $?
0
```

It's a quick test. Converting `go.mod` returns 1, while converting a file from test data returns 0.

**Comment by kkovaletp** [comment] 2024-08-22 05:29
Once we have ImageMagick and Jellyfin-FFmpeg workers merged, we might update the logic of the source media formats processing and move all of them to the corresponding workers instead of processing them by our code.
I believe that these tools would provide better results. Another benefit would be to decrease our codebase and potentially decrease the space for bugs (less code - less bugs).

**Comment by googollee** [comment] 2024-10-07 09:48
`photoview` could run without any external clis (Exiftools/Imagemagick/FFmpeg). Of course it won't process some formats without those clis. Besides those features, it could work with [some basic types](https://github.com/photoview/photoview/blob/f8b9590aa97da1413461f8a3239b2c54d715b4b1/api/scanner/media_type/media_type.go#L247). If we depend on external clis to check the type of files, we may lose this feature.

We should keep those basic formats checking with ext name.

**Comment by kkovaletp** [comment] 2024-10-07 14:08
I see your point and agree that this possibility will be lost after this ticket is implemented.
However, what are the practical use cases of having Photoview installed on the host (because in the Docker image, everything is pre-installed), but not installing ImageMagick and FFmpeg?
Ok, a user might not have videos and doesn't want this functionality, so in this case, it is clear why FFmpeg is missing. Also, the `PHOTOVIEW_DISABLE_VIDEO_ENCODING` would be set to `1`, so this functionality is intentionally disabled.
But what is the reason for not installing the ImageMagick?

On the other side, moving the formats detection, combined with the media processing, to the corresponding tools would noticeably increase the list of supported media, quality of media processing, and decrease maintenance efforts for our code with no additional efforts from our side in the future. 

I see much more benefits from this ticket implementation. If I miss something, please let me know)

**Comment by googollee** [comment] 2024-10-07 15:52
I agree with you that most users should use Docker images. In my opinion, I'd like to limit the support on Docker image deployment only, for simplicity. I also hope to deprecate environments like `PHOTOVIEW_DISABLE_VIDEO_ENCODING` and `PHOTOVIEW_DISABLE_RAW_PROCESS` if we support Docker image deployment only, since handling data when those environments change is complex, like https://github.com/photoview/photoview/issues/677#issuecomment-2391148956. 

So my question is, should we declare that we only support the deployment with Docker image?

**Comment by kkovaletp** [comment] 2024-10-07 17:16
Sorry for the possible misunderstanding, but I didn't mean that.
Yes, the default and the most used deployment type is (and should be) the Docker image. But also, in parallel, we still should support the direct deployment scenarios for the cases, when Docker is not available or not efficient. This type of deployment should be considered advanced and used with additional notice of limited support and high chances of dealing with some installation issues (like missing dependencies, additional configuration steps, etc.).

Regarding the 2 mentioned env vars:
- `PHOTOVIEW_DISABLE_VIDEO_ENCODING`: I see the next practical case when a user would want to use it and disable video processing: when Photoview runs on a low-performance server and running video processing takes not an acceptable amount of system resources
- `PHOTOVIEW_DISABLE_RAW_PROCESS`: Currently, RAW and regular pictures process differently (by an external worker vs. by our code), so even after we switched from the DarkTable, available only on some of the supported archs and used more resources, to the more efficient and available on all archs ImageMagick, in theory, I still could imagine a case, when there is no ImageMagick on the system. But in practice, I don't see benefits and reasons for that. So, after we implement this ticket, I think that we could remove this variable as well: when all pictures (RAW and regular ones) are processed by the same worker, there is no reason to disable RAW processing.

**Comment by googollee** [comment] 2024-10-08 09:17
Currently, we have 3 external tools: `exiftool`/`ImageMagick`/`FFMpeg`. We could also use `ImageMagick` to extract exif info, and deprecate `exiftool`.

**Comment by kkovaletp** [comment] 2024-10-08 13:54
Unfortunately, removing exiftool won't work for us, as exiftool can extract data from pictures and videos. There is a ticket somewhere (if I won't find it, I'll submit a new one) to extract and save exif data for videos as well.

I've tried ffprobe, but it doesn't show all the same info, as exiftool does

**Comment by googollee** [comment] 2024-10-08 14:13
OK. Good to know that. Then I'd like to document the requirement somewhere like:

- photoview depends on `exiftool` and `ImageMagick`.
- photoview can process videos if `FFMpeg` is available.

**Comment by googollee** [comment] 2024-10-15 10:35
ImageMagick can list all supporting formats with `magick identify -list format`. We could filter all `read support` when `photoview` launches, and use `magick identify -print '%m' <file>` to get the format. Of course we should have a group of basic formats (JPEG/PNG/TIFF/WEBP/BMP/HEIC/GIF).

The problem is, it can't split that list by video/image. Even most of video formats have `Video` in the description, I can find some don't have:

```
AVI  r--   Microsoft Audio/Visual Interleaved
```

It also misses some Video format like `ogg`.

It may have similar issues with Raw formats.

I'd like to keep the list of media types, but turn the list in a readable format, like:

```
<mime type> <ext names> <flag type, B for basic support, R for RAW format, W for browser support>
# Example
image/tiff tif,tiff B
```

And use this list to generate `media_type.go` during compiling.

**Comment by kkovaletp** [comment] 2024-10-16 13:49
The main idea of this ticket is to support all formats, ImageMagick and FFmpeg support, and automatically align this "list" of supported formats with the currently installed versions of both tools. This means that if tomorrow a new format is added to the new version of one of these tools, Photoview starts to support it once this version is installed on the server and used by Photoview.

> ImageMagick can list all supporting formats with `magick identify -list format`. We could filter all `read support` when `photoview` launches, and use `magick identify -print '%m' <file>` to get the format.

This approach limits the idea to the compilation time (so, Photoview starts to support a new format only after it is rebuilt with the new tool version) and the user will get it with the new image or after reinstalling in the case of the direct deployment.
Also, there is additional complexity in this approach implementation: we need to run and process the results of 1 more external command, which increases the level of interface dependency: + 1 additional interface to the external tool, which can be changed in the future and we'll have an urgent issue because of that.

I still think that probing a source file by `ffprobe` and `magick`, followed by processing the file by the best suitable tool, based on the probing results, looks much simpler from the code perspective and dynamic. There is an open question of how to decide the best tool if both successfully probed the file. We'd need to test such formats and see how to distinguish them based on the reports from both tools. I hope that there will be a clear indication of the media type (image, video, or sound) in these reports.

> I'd like to keep the list of media types

Why do you like to have the semi-static list? What benefits does it provide?

**Comment by googollee** [comment] 2024-10-16 19:26
> I hope that there will be a clear indication of the media type (image, video, or sound) in these reports.

As far as I know, there is no easy way to say a file is an image/video/sound. Most of file formats are container formats, like avi/mkv/tiff/webp/png. Some times like Matroska use `.mkv` for video(motion and audio) and `.mka` for audio only, but both `.mkv` and `.mka` show as Matroska format.

I don't think it's a good way to probe a file by `ffprobe` and `magick`. Depending on the order, it could treat a video as an image, or reverse.

> Why do you like to have the semi-static list? What benefits does it provide?

I thought you found the `media_type.go` hard to maintain. But I guess it's not for this issue.

**Comment by kkovaletp** [comment] 2024-10-17 06:09
> As far as I know, there is no easy way to say a file is an image/video/sound.

That is true, however, I still think that in most cases it is easy to distinguish the content inside between audio/video and image types based on `ffprobe` and `magick` reports: 
- `ffprobe` shows streams in the report, so, if there is a video stream, that is a clear sign that this is a video
- we don't support audio, so we don't care about a lot of audio formats and could categorize them as not supported
- if after parsing the `ffprobe` report we didn't categorize the file as video or audio (not supported), we could try to convert it by `magick` as an image and don't even probe it: if it succeeds, that was an image, if not, it is something else and we don't care

> I don't think it's a good way to probe a file by `ffprobe` and `magick`. Depending on the order, it could treat a video as an image, or reverse.

Do you still see an issue here with the algorithm, described above? I guess that we need to play with several examples to find out the best algorithm and keywords for the report...

> I thought you found the `media_type.go` hard to maintain. But I guess it's not for this issue.

Yes, that is not the most important aspect here.

**Comment by googollee** [comment] 2024-10-17 07:47
> Do you still see an issue here with the algorithm, described above?

Yes. From the description, we depend on `ffprobe`. If that bin doesn't exist, we can't support any videos, even with formats that do not need to be transferred. We still support the env without `ffmpeg`, which doesn't have `ffprobe` too.

IMO, we need to make the recognition process intuitive, rather than covering all cases. The most intuitive process is identifying by extension name, which is easy to explain. Besides introducing new formats, do you have any case that this process doesn't work well?

BTW, one benefit of the semi-static list is that it's easy for non-developer users to contribute.

**Comment by kkovaletp** [comment] 2024-10-17 08:17
> We still support the env without `ffmpeg`, which doesn't have `ffprobe` too.

Good point. In this case, we simply skip the `ffprobe`-related steps and try to convert the file as an image. If it is converted, that is an image, if not - we don't support it. What do you think?

> The most intuitive process is identifying by extension name

From my PoV, it is not, as we already have A LOT of different file extensions, some of which are containers, so it doesn't make things more clear... I think that relying on the tools, designed to process media, is the most reliable and intuitive approach:
- if a video processing tool recognizes the file as a video, it is a video
- if an image processing tool is able to convert the file to a picture, taking into account the result of the previous step (if available), it is a picture.
However, I can imagine the case, when a user disabled video processing with the intention to skip those files, but not to save resources during the job run (so, he/she intentionally doesn't want them to appear in the albums), while ImageMagick might (and I'm not sure about this, just assuming) extract a picture from the video, adding it to the album. This is the corner case, which we have to mention and advise users to add unwanted file patterns to the ignore file, which is the right way to exclude some content from the scanner's scope.

> Besides introducing new formats

This is a major case for us based on plenty of issues, requesting to add the support for some formats or enhance the support with covering additional corner cases.

> benefit of the semi-static list is that it's easy for non-developer users to contribute

In practice, it almost never happened before and I believe that it won't happen in the future. Also, it is easy to make mistakes there, which might lead to many invalid difficult to reproduce issues

**Comment by googollee** [comment] 2024-10-17 08:59
> In this case, we simply skip the ffprobe-related steps and try to convert the file as an image. If it is converted, that is an image, if not - we don't support it.

That may be not the right way. Since ImageMagick supports a lot of video formats, I guess it converts one of video frames to an image, which leads `photoview` to treat that video as an image. I don't think it's just a corner case.

> requesting to add the support for some formats or enhance the support with covering additional corner cases.

I agree that this is the real requirement. Autodetection is one protential solution to solve it. I'd like to discuss solutions based on this requirement. Do you agree?

> Also, it is easy to make mistakes there, which might lead to many invalid difficult to reproduce issues.

Since we have a review process, I don't see it's easy to introduce mistakes. The list parses to code files like `media_type.go`, and compiles to the binary. It's not loaded during launching.

**Comment by kkovaletp** [comment] 2024-10-17 09:31
> ImageMagick supports a lot of video formats, I guess it converts one of video frames to an image, which leads `photoview` to treat that video as an image

Well, 1st - we need to test it, as for now, this is just an assumption from both of us. Does the same command, as we use to convert images, will extract a preview frame from a video? I think that the most probability is that it fails, as ImageMagick would require the command to contain additional parameters.
2nd - if that would work and extract preview images, this is not necessarily a mistake. See my comment about the ignore file usage. Yes, the behavior of the product changes here, but it still might be correct. We might need to discuss it if the previous statement is confirmed in practice.

> I'd like to discuss solutions based on this requirement. Do you agree?

Sure! We're here for that) I believe that discussing the solution and its alternatives before the implementation allows to choose the best and the most optimal way to implement the requirement.

> Since we have a review process, I don't see it's easy to introduce mistakes.

When I wrote that comment, I assumed the config to be generated at the product compilation time based on static presets and the lists of supported formats from both workers and later be available for user edits, so that the next scan job reads the latest version of the config and uses it during the scan. That was my understanding of non-development modifications.
However, when I wrote that it almost never happened, I meant the PR way of changes proposal. I don't believe that non-devs would create PRs, as the PR workflow is too complex and tricky for non-devs.

As we have `master` and the latest released tagged images auto-rebuild weekly, the semi-static approach, based on static presets and lists of supported formats from both tools, might work (assuming that users regularly update the Photoview version), however, I assume pretty complex and difficult to maintain code to parse those reports: as you mentioned before, they contain not so clear categorization of media types, so we'd need to define complex conditions and many keywords to handle that...

**Comment by googollee** [comment] 2024-10-21 20:38
With testing functions recently, I think this is not a high-priority issue. I'd like to work on other front-end issues like jumping from images in a Geo to an album or switching MapBox to other venders. I'd like to remove it from the blocking column.

**Comment by kkovaletp** [comment] 2024-10-22 12:36
Why do you think so? I don't agree, as currently, we don't support many media formats, supported by our workers.

**Comment by googollee** [comment] 2024-10-22 13:38
We don't agree on a good solution now. It's a good direction to invest, but it's not necessary to block the release.

**Comment by kkovaletp** [comment] 2024-10-28 15:55
Hey, this is a good idea. Actually, I knew about this Linux tool... Why I didn't think to use it in the scope of this functionality?...
I'll test it and share the results, however, now I'm interest the most about the results of probing different RAW files... I'm not sure they all can be detected correctly...

**Comment by kkovaletp** [comment] 2024-10-28 18:24
> I guess we can treat all `tiff` and `dng` as raw formats.

Well, if we're going to pass all image processing to ImageMagick, then it doesn't really matter what format it reports in as long as it falls under the `image` category.

**Comment by googollee** [comment] 2024-10-28 22:00
I put more test results here:

```
$ file --mime-type 03FA18D2-9549-4718-A5F9-672C07EA0BEC.raf  # Fujifilm RAW file
03FA18D2-9549-4718-A5F9-672C07EA0BEC.raf: image/x-fuji-raf
$ file --mime-type 0EAE48B6-A89E-4340-B7BA-E5E8E2C4747F.nef  # Nikon Raw file
0EAE48B6-A89E-4340-B7BA-E5E8E2C4747F.nef: image/tiff
$ file --mime-type DSCF2048.MOV  # Fujifilm video file
DSCF2048.MOV: video/quicktime
$ file --mime-type _DSF1682-Enhanced-NR.dng  # HDR file by Lightroom
_DSF1682-Enhanced-NR.dng: image/tiff
$ file --mime-type recoverable.jpg
recoverable.jpg: image/jpeg
```

For images, I want to keep a group of mimetypes as basic types, meaning browsers support showing them. Currently, they are:

```
var WebMimetypes = [...]MediaType{
        TypeJpeg,
        TypePng,
        TypeWebp,
        TypeBmp,
        TypeGif,
}
```

For other images
- if they have a counterpart file with one of the basic types, use the counterpart file directly.
- convert to a jpeg file with `ImageMagick` if possible.

For generating small jpeg files:
- if it's possible, use `ImageMagick` to resize
- if not, use `golang.org/x/image`, which may not succeed with some broken jpegs.

Let's get the agreement on the image part first.

**Comment by kkovaletp** [comment] 2024-10-29 19:22
I still have the task of testing my testing media set with the `file` tool in my short TODO list. I'll post the results here.

> I want to keep a group of mimetypes as basic types, meaning browsers support showing them

Did I understand you correctly, that these files are not going to be converted to the high-res JPG, but simply copied there as is? What about thumbnails?...

> For generating small jpeg files:

... Or is this related to all types of images?

> * if it's possible, use `ImageMagick` to resize

It would be a big surprise for me if it is not possible, but if it actually is not, we still can run ImageMagick to auto-fix broken files, and then process the result as usual

**Comment by googollee** [comment] 2024-10-30 08:04
> these files are not going to be converted to the high-res JPG, but simply copied there as is? What about thumbnails?

Yes. As they are supported by browsers, we could show original files without any processing. Thumbnails are covered by `generating small jpeg files`.

> if it's possible, use ImageMagick to resize

The user environment may not install `ImageMagick`. If no `ImageMagick` installs, fallback to `golang.org/x/image`.

**Comment by kkovaletp** [comment] 2024-10-30 18:24
> The user environment may not install `ImageMagick`

Do you see a practical reason or a use case, when users don't want to install ImageMagick?
I'd like to make it a mandatory and unavoidable tool. Maybe I missed something, but from my point of view, in this case, we can really simplify our backend code for the scanner workflow. This makes our project easier to maintain and unconditionally gives us all the benefits of ImageMagic.

**Comment by googollee** [comment] 2024-10-30 19:19
Since we can't build ImageMagick with `photoview` binary, I'm afraid users can always run `photoview` directly without installing ImageMagick. Even we declare a list of mandatory tools, the code still needs to cover the case of missing tools. We either refuse to run the binary without tools, provide a fallback, or show that case clearly in logs. I prefer to provide a fallback here.

**Comment by kkovaletp** [comment] 2024-11-02 12:20
Finally, I've tested my testing lib with the `file` tool. Here are the results:
It looks like all the media files detected correctly and we can use this tool.
```bash
root@photoview:/home/photoview# find /photos -type f -exec file --mime-type {} \;
/photos/Viber/1c6db00ce0ac5c.jpg: image/jpeg
/photos/Viber/1c6dbb1856de65.mp4: video/mp4
/photos/Viber/thumb0-1c6db2060848bb.jpg: image/jpeg
/photos/Viber/1c6db91c6b82a7.jpg: image/jpeg
/photos/Viber/.DS_Store: application/octet-stream
/photos/Viber/1c6db41c30027c.mp4: video/mp4
/photos/Viber/1c6dbca359ab95.jpg: image/jpeg
/photos/Viber/thumb_206034a8fe4df9.jpg: image/jpeg
/photos/Viber/1c6daf2988fe68.jpg: image/jpeg
/photos/Viber/1c6db00ce24ebf.jpg: image/jpeg
/photos/Viber/1c6dbb92c82816.png: image/png
/photos/Viber/f58574e548778ea9c81c5cd9f4ff113030506.jpg: image/jpeg
/photos/Viber/thumb0-1c6dbbdc613e63.jpg: image/jpeg
/photos/Viber/GIF-62c21638d95d44be09be9ec02394bedd.gif: image/gif
/photos/Viber/1c6db0f5ba18cc.jpg: image/jpeg
/photos/Viber/1c6db00ce27fb3.jpg: image/jpeg
/photos/main/bing-wallpapers/info.xml: text/xml
/photos/main/bing-wallpapers/.DS_Store: application/octet-stream
/photos/main/bing-wallpapers/default-OHR.BisonYellowstone_ROW7352614492_UHD.jpg: image/jpeg
/photos/main/20240401_183405.heic: image/heic
/photos/main/IncorrectGPS.jpg: image/jpeg
/photos/main/20221109_141326.heic: image/heic
/photos/main/.DS_Store: application/octet-stream
/photos/main/20240608_105354-8K.mp4: video/mp4
/photos/main/.localized: inode/x-empty
/photos/main/test-video copy1.mp4: video/mp4
/photos/main/santa-claus-list.gif: image/gif
/photos/main/IMG_3133.jpg: image/jpeg
/photos/main/VID_20221224_163829.mp4: video/mp4
/photos/main/DS_Store: application/octet-stream
/photos/main/VID_20221224_162851.mp4: video/mp4
/photos/main/VID_20221224_165642.mp4: video/mp4
/photos/main/IMG_20221224_170255.jpg: image/jpeg
/photos/main/IMG_3218.jpg: image/jpeg
/photos/main/303650519-44cd5a6d-4f13-482d-b12f-8364052a4303.jpg: image/jpeg
/photos/main/IMG_3219.jpg: image/jpeg
/photos/main/IMG_20221224_214646.jpg: image/jpeg
/photos/main/IMG_20221224_162437.jpg: image/jpeg
/photos/main/IMG_20221224_190459.jpg: image/jpeg
/photos/main/IMG_3196.jpg: image/jpeg
/photos/main/IMG_20221224_173515.jpg: image/jpeg
/photos/main/IMG_3195.jpg: image/jpeg
/photos/main/VID_20221224_164451.mp4: video/mp4
/photos/main/IMG_3211.jpg: image/jpeg
/photos/main/IMG_20221224_211325.jpg: image/jpeg
/photos/main/IMG_3199.jpg: image/jpeg
/photos/main/IMG_20221224_163523.jpg: image/jpeg
/photos/main/IMG_20221224_193607.jpg: image/jpeg
/photos/main/IMG_20221224_172942.jpg: image/jpeg
/photos/main/IMG_3213.jpg: image/jpeg
/photos/main/IMG_20221224_211256.jpg: image/jpeg
/photos/main/IMG_3203.jpg: image/jpeg
/photos/main/IMG_20221224_202438.jpg: image/jpeg
/photos/main/VID_20221224_164119.mp4: video/mp4
/photos/main/IMG_20221224_162304.jpg: image/jpeg
/photos/main/IMG_20221224_193512.jpg: image/jpeg
/photos/main/IMG_20221224_151451.jpg: image/jpeg
/photos/main/IMG_20221224_191933.jpg: image/jpeg
/photos/main/IMG_20221224_172104.jpg: image/jpeg
/photos/main/IMG_3117.jpg: application/octet-stream
/photos/main/VID_20221224_163616.mp4: video/mp4
/photos/main/VID_20221224_164353.mp4: video/mp4
/photos/main/IMG_3128.jpg: image/jpeg
/photos/main/IMG_20221224_211237.jpg: image/jpeg
/photos/main/IMG_0482_raw.CR3: application/octet-stream
/photos/main/20240401_183338.heic: image/heic
find: '/photos/main/Photos Library.photoslibrary': No such file or directory
/photos/main/jorrbox-jorrparivar.gif: image/gif
/photos/main/IMG_0928-iPhone-15.HEIC: image/heic
/photos/main/santaiscomin-santa.gif: image/gif
/photos/main/sample1.RAF: image/x-fuji-raf
/photos/main/wrong-GPS-exif.jpg: image/jpeg
/photos/main/wrong-GPS-exif.jpg_original: image/jpeg
/photos/main/test-video.mp4: video/mp4
/photos/main/webp-colors-bug-samples/test.webp: image/webp
/photos/main/webp-colors-bug-samples/test.jpg: image/jpeg
/photos/main/webp-colors-bug-samples/thumbnail_webp.jpg: image/jpeg
/photos/main/webp-colors-bug-samples/thumbnail_jpg.jpg: image/jpeg
```

**Comment by kkovaletp** [comment] 2024-11-02 13:05
> Since we can't build ImageMagick with `photoview` binary, I'm afraid users can always run `photoview` directly without installing ImageMagick.

Why do you think that this is always going to happen in the direct deployment case?
We have a list of mandatory libs and tools to be installed on the system. We expect them to be installed.

> the code still needs to cover the case of missing tools. We either refuse to run the binary without tools, provide a fallback, or show that case clearly in logs. I prefer to provide a fallback here.

Sure, I agree that this is a good design to verify all prerequisites at the init stage and clearly notify if something is missing in the log.
As to me, providing a fallback means that the tool is optional and we, in fact, should maintain both cases. This will technically work fine, but it is much more expensive from the project support PoV.
Please explain why would you prefer this option? Do you see some use cases, where we support the deployment in general, but it is not possible to install ImageMagick? Any other reason, that I don't see?

**Comment by googollee** [comment] 2024-11-02 16:21
> providing a fallback means that the tool is optional and we, in fact, should maintain both cases.

I'm discussing what `photoview` should do if dependencies are missing. There are 3 choices:

1. Quit the program when initializing with a clear log.
2. Continue running and providing a fallback function.
3. Continue running and log an error when running functions requiring dependencies.

I prefer 2 (if possible) > 3 > 1. Which do you prefer?

**Comment by kkovaletp** [comment] 2024-11-02 17:42
Thanks for the summary.
In short, I'd prefer the next order: 3 > 2. I'd not choose option 1, as it doesn't look appropriate in the case of ImageMagick: it is going to be mandatory for the scanner component, but not for the Photoview itself, so it looks not correct to block the product completely if only 1 module cannot work and only with pictures.

Then, to choose between options 2 and 3, I considered the next points:
- Both allow Photoview to run in general
- Option 2 means that we keep most of the current code and dependencies as a fallback solution. This leads to the need to fix remaining bugs in the current implementation, even if they are not reproducible with ImageMagick worker. Also, we have to keep maintaining this code in the future, updating its dependencies and making sure that our new features won't break it. This requires too much effort long term.
- Option 3 allows us to drop a noticeable part of the image processing code (and probably some of the dependencies). This (from my PoV)  simplifies the product maintenance, add more flexibility in making decisions on future architectural changes, and fixes most part of image processing bugs in the backlog (I hope).

This is why option 3 looks like a better choice. But I might miss some use cases or aspects, so please explain why you prefer option 2 over the 3rd one.

**Comment by googollee** [comment] 2024-11-02 21:44
I'm OK with option 3 too. Do we have a way to show a flag on the webpage? Or should we show a warning on the setting page?

**Comment by kkovaletp** [comment] 2024-11-03 06:47
As far as I know, we only have pop-up messages with backend status notifications: #965. we can use them here as well (and this is a good idea because now we write about missing workers only in the log).

**Comment by kkovaletp** [comment] 2024-12-28 08:46
@googollee, after the #1124 is merged, do you think that this issue is fully covered and can be closed?

**Comment by googollee** [comment] 2024-12-30 15:16
This issue is fixed. The remain part will be traced by #1089.

**Closed by googollee** 2024-12-30 15:16 UTC
Labels: help wanted, discussion, API, scanner, high priority, needs information, go, improvement
