### ISSUE TITLE
Deleted picture are still displayed

### ISSUE THREAD

**Issue by ced455** [photoview/photoview#682] opened 2022-04-21 12:29 UTC
Hello,

I deleted a few thousand pictures recently and I still could see the thumbnails, I then deleted all of them, performed a new scan, and now the pictures are still there but blurry, same for the faces.
I obviously ran a full scan.

I am running it on docker V2.3.12 , and mariadb latest

![image](https://user-images.githubusercontent.com/26870023/163437401-a01f669e-a359-4254-b758-4e8307d2af90.png)
![image](https://user-images.githubusercontent.com/26870023/163437512-2f0231ee-0d95-4450-85ea-1ebd7272daec.png)

I would like to avoid deleting the database since it took me quite some time to label and merge all my faces.  
Is there a way to trigger a scan that detect deleted images ?

thank you.

**Comment by Flaxee** [comment] 2022-04-23 13:29
I also experienced this recently when I deleted a few photos from a folder with many thousands of photos. The thumbnails were still displayed, and when I deleted the thumbnails, the blurhash was displayed. I logged into the Mariadb database and there was still references to the deleted images.

I then deleted a photo from another folder that's connected to another user, and that was correctly  removed from photoview after a scan.

I don't know why it works correctly for one folder/user but not the other, since it's the same installation of photoview and mariadb. The only difference between them is that the first folder contains thousands of photos and the other only a few hundred.

I'm also running the latest version of Photoview in docker, and Mariadb 10.6.

**Comment by Avasz** [comment] 2022-05-12 13:26
![image](https://user-images.githubusercontent.com/2859879/168084542-4aea8c4a-68d0-4f86-a0e9-1b28bd90c53e.png)

Jokes apart,

I am running `Release Version: 2.3.12` in Docker, and have removed the `:ro` part.
But I see no option to delete the photos. Am I missing something?

**Comment by Flaxee** [comment] 2022-05-12 16:13
@Avasz it's not possible to delete photos from within Photoview. You have to delete them from the filesystem and then do a rescan of the folder in Photoview.

**Comment by Avasz** [comment] 2022-05-13 05:05
Ah ok. Thanks for the clarification!

**Comment by hupfdule** [comment] 2022-07-06 12:56
I have a similar problem.
I have some videos in a library that somehow were not correctly converted. I see the thumbnail, but the video cannot be played.
I deleted these videos and rescanned. But the thumbnail is still there.
I put the videos back into the filesystem and rescanned. But they are _not_ rescanned as photoview thinks they are still there.

**Comment by mrkaryo** [comment] 2024-01-03 00:46
Hello all! 
Any ideas about this one? It seems removed media leave behind empty white boxes. Clicking on the info button on them gives the message:
`Server error: could not get media by media_id and user_id from database: record not found at (media)`

**Comment by DaCHack** [comment] 2024-01-07 01:33
I could imagine that instead of editing the corresponding rows in the database as I described in the other issue
https://github.com/photoview/photoview/issues/56#issuecomment-1879906294
you could also delete these rows, but certainly to be confirmed by developers.

**Comment by kkovaletp** [comment] 2024-06-08 07:10
@ced455, @DaCHack, and others here, do you still have this issue while using the `master` version of the product? I've tested media deletion several times on my test instance and it works fine: after the next scan the removed media disappears from Photoview.
Please let me know if this is still an issue in some complex or large setups. If not, I'll close it as completed.

**Comment by kkovaletp** [comment] 2024-09-22 08:27
Closing the issue as completed, as now it is fixed by some of the already merged PRs

**Closed by kkovaletp** 2024-09-22 08:27 UTC
Labels: bug, discussion, scanner, needs information, pending response
