### ISSUE TITLE
Processing stops in at the same spot in files

### ISSUE THREAD

**Issue by jbdubbs** [photoview/photoview#727] opened 2022-08-08 20:34 UTC
**Describe the bug**
Processing of new photos/videos stops at around the same spot on a new install.  I have a large photo repository that I've tried to share in a number of ways to avoid the issue.  All are under Proxmox: VM, unprivileged container, privileged container.  All are shared with SMB protocol to /mnt/photos, which I pass through to the Docker container.  

It gets through exactly 2028 of my 14100 images and videos, then stops with the following:

```
2022/08/08 15:30:54 Processing photo: /photos/20171223_201810_HDR.jpg

2022/08/08 15:30:55 Processing video: /photos/20171223_9665(1).mp4

2022/08/08 15:30:57 Processing photo: /photos/20171225_065106_HDR.jpg

2022/08/08 15:30:59 Processing video: /photos/20171225_070006.mp4

2022/08/08 15:30:59 Job finished

2022/08/08 15:30:59 Queue waiting for lock

2022/08/08 15:30:59 Queue running: in_progress: 0, max_tasks: 3, queue_len: 0

2022/08/08 15:30:59 generating 50 blurhashes

2022/08/08 15:31:05 generating 50 blurhashes

2022/08/08 15:31:08 Did not find auth-token cookie

2022/08/08 15:31:08 POST 200 localhost/api/graphql 501.843µs unauthenticated

2022/08/08 15:31:10 generating 50 blurhashes
```
I even removed the last file to see if that had something to do with it, and it stopped at the file right after it instead.  The file I removed was a 400+MB mp4, the one that it stopped at next was a small jpeg.

**To Reproduce**
1. Start Scan
2. Let it run
3. Check logs, notice the spot it stopped

**Expected behavior**
Continue past this seemingly file agnostic stopping point and process the rest of the files.

**Your environment:**
Feel free to remove and add what you think might be useful.

Release Version

Version: 2.3.13 ([446ef9a4]
Build date: 2022-07-26T18:26:27Z

 - Are you using Docker? yes
 - Database MariaDB 10.5
 - Browser Firefox or Chrome
 - Version 100+
 - Proxmox VE 7.2
 - Ubuntu 22.04 container or VM

**Comment by TheKeyLimePie** [comment] 2022-08-09 18:11
Hi,
I've experienced the same problem. With smaller albums everything works just fine, but when processing a larger album with a couple of thousands of images, it always stops processing images at the same point.

**My setup:**
* Are you using Docker? Yes
* Database MariaDB 10.5.16
* Browser Chrome
* Version 2.3.13 ([446ef9a4](https://github.com/photoview/photoview/commit/446ef9a46485bd18bb1c6890d485344786a4e90c))

What I did to "fix" this problem is to downgrade to version 2.3.12 (https://github.com/photoview/photoview/commit/0b9d04eff2b6f896a70e8d081b6706dc4068f732) in my docker-compose configuration. The processing job then continued.
Something I've noticed in the log after downgrading Photoview is this error message at the point where the current version stopped working:
> photoview_1  | 2022/08/09 17:56:37 ERROR: Failed to begin database transaction: failed to process photo (/photos/Camera/IMG_20180812_002413~2.dng): creating high-res cached image: encoding image using: /usr/bin/darktable-cli [/photos/Camera/IMG_20180812_002413~2.dng /app/cache/2/3255/highres_IMG_20180812_002413~2_dng_1VxRwHpb.jpg --core --conf plugins/imageio/format/jpeg/quality=70 --configdir /tmp/photoview-darktable1071851445]: exit status 1

But maybe it's just another error not being the cause for the issue discussed here.
Nevertheless, it seems to be a bug introduced with 2.3.12
> Changelog: "Improve how scanner tasks are structured internally"

**Comment by jbdubbs** [comment] 2022-08-09 21:40
@TheKeyLimePie Thank you for the solution.  You seem to be absolutely correct.  Downgrading to 2.3.12 fixed the issue and the error I get is similar to yours on the file that 2.3.13 stopped the process at:

`2022/08/09 21:36:12 ERROR: Failed to begin database transaction: failed to process photo (/photos/20171225_070006.mp4): failed to read metadata for original video (20171225_070006.mp4): read video stream metadata: could not read video metadata (20171225_070006.mp4): error running ffprobe [] exit status 1`

**Comment by PJ-Watson** [comment] 2022-08-11 12:14
I'm just tagging in a couple of related threads for future reference (#708 #729 ), and doing a bit of brainstorming:

> It gets through exactly 2028 of my 14100 images and videos, then stops with the following:
...
>``` 2022/08/08 15:30:59 Queue running: in_progress: 0, max_tasks: 3, queue_len: 0 ```
...
> I even removed the last file to see if that had something to do with it, and it stopped at the file right after it instead. The file I removed was a 400+MB mp4, the one that it stopped at next was a small jpeg.

A couple of things it might be worth trying here:
- Setting the number of concurrent workers to 1, to see if that changes anything.
- Renaming a folder, so that it'll scan the first 2028 files in a different order. 

The fact that there's an error message in 2.3.12 at the _exact same point_ it stops scanning in 2.3.13 seems a bit too unlikely to be a coincidence!

For the 2028 pictures photoview does scan, do they appear as normal, or are they not displayed properly, as in #708 ? (similarly for the images it _doesn't_ scan)

**Comment by jbdubbs** [comment] 2022-08-11 19:40
@PJ-Watson 

Re-downloaded 2.3.12 to test some of the things you mentioned.

Setting the number of concurrent workers to 1 does not change the outcome.

Unfortunately, all my files are flat in the directory and I don't know how the scanning process works.  Are directories scanned first, followed by all the files in the parent?  If so, I can attempt to place offending files in different named folders to manipulate the order.

All of the images scanned do appear normally, as opposed to #708

**Comment by PJ-Watson** [comment] 2022-08-12 00:17
> @PJ-Watson
> 
> Re-downloaded 2.3.12 to test some of the things you mentioned.
> 
> Setting the number of concurrent workers to 1 does not change the outcome.
> 
> Unfortunately, all my files are flat in the directory and I don't know how the scanning process works. Are directories scanned first, followed by all the files in the parent? If so, I can attempt to place offending files in different named folders to manipulate the order.
> 
> All of the images scanned do appear normally, as opposed to #708 . Images that were "found" but not processed show up as a white box, possibly a plain white blurhash, but not displaying a broken image.

Okay, thank you! That does narrow it down a bit, although I'm still not entirely sure where it's going wrong. Just writing down some of my working (and also in case @viktorstrate has any thoughts on where it might be running into problems):
 - The scanner queue is set up to generate blurhashes only after finishing all the previous jobs in the queue, so something must be cutting the jobs short (looking at your first post in this thread).
 - The root directories are scanned first (any filepath that you put in when you first set it up), then sub directories, and then it iterates through files in each directory.
 - It only uses one worker per directory, so if you've got a flat directory (all ~14k images in one folder), then it'll work its way through this sequentially. This does also mean that if anything throws an error part way through scanning or processing, the job will just stop there.
 - If it's finding _all_ of your images, but not processing all of them, I suspect it might be a couple of files throwing errors when it generates thumbnails. If you try separating it into multiple directories, each with ~1000 photos, does that change anything?
 - The other option is it's running into some kind of timeout with such a large directory, but I'll try and check that it's not a problem with anything else first.

> `2022/08/09 21:36:12 ERROR: Failed to begin database transaction: failed to process photo (/photos/20171225_070006.mp4): failed to read metadata for original video (20171225_070006.mp4): read video stream metadata: could not read video metadata (20171225_070006.mp4): error running ffprobe [] exit status 1`

Errors like this should show up in 2.3.13, so it's interesting that it doesn't. If you search the logs for "ERROR" or "failed", does anything appear?

**Comment by viktorstrate** [comment] 2022-08-12 06:33
@PJ-Watson Thank you for your detailed troubleshooting thoughts and findings.
I think the problem lies with the following loop where errors cause a `return` rather than a `continue`.

https://github.com/photoview/photoview/blob/1a05b353e6971b817dc832f458e6c8fabfd8ddba/api/scanner/scanner_album.go#L103-L134

At a quick glance the solution would probably be to collect the errors into an array instead of returning on the first one and not continuing for the rest of the images.
For better flexibility and structure a new [ScannerTask](https://github.com/photoview/photoview/blob/1a05b353e6971b817dc832f458e6c8fabfd8ddba/api/scanner/scanner_task/scanner_task.go#L16) event could be added for handling errors, then the notification task can use that to send back an error notification to the user and in the future a better error handling system can make use of it.

@PJ-Watson do you want to work on this? Otherwise I will take a look at it, one of the next days when I have better time.

**Comment by viktorstrate** [comment] 2022-08-12 15:03
> Yep, I'm happy to try and tackle this; understanding the scanner system was something I planned to do before going back to the face recognition side of things.

Perfect, feel free to ask if you have questions. You can also reach me (and others) on the Discord channel if you use that.

> It might be good to have a notification along the lines of `Error processing {x} media files in album {y}. Please check the log for further details.`

Good idea, and we can also always change the structure of the task interface later if need be.

**Comment by jbdubbs** [comment] 2022-08-12 20:13
@PJ-Watson @viktorstrate 

Thank you so much!

I see there has been significant movement since I last logged in.  Do you need any further troubleshooting from me?

**Comment by jamolnng** [comment] 2022-10-05 16:03
> @PJ-Watson Thank you for your detailed troubleshooting thoughts and findings. I think the problem lies with the following loop where errors cause a `return` rather than a `continue`.
> 
> https://github.com/photoview/photoview/blob/1a05b353e6971b817dc832f458e6c8fabfd8ddba/api/scanner/scanner_album.go#L103-L134
> 
> At a quick glance the solution would probably be to collect the errors into an array instead of returning on the first one and not continuing for the rest of the images. For better flexibility and structure a new [ScannerTask](https://github.com/photoview/photoview/blob/1a05b353e6971b817dc832f458e6c8fabfd8ddba/api/scanner/scanner_task/scanner_task.go#L16) event could be added for handling errors, then the notification task can use that to send back an error notification to the user and in the future a better error handling system can make use of it.
> 
> @PJ-Watson do you want to work on this? Otherwise I will take a look at it, one of the next days when I have better time.

A basic hack of commenting out the `return err` and replacing it with `continue` appears to have worked for me. @PJ-Watson are you still working on this?

**Comment by martadinata666** [comment] 2022-10-07 05:47
I tried using `:edge` tag because v2 show gray images, is this considered corrupt?
```
2022/10/07 12:36:05 ERROR: Failed to scan album: process media database transaction: could not create thumbnail cached image: invalid JPEG format: short Huffman data
```

**Comment by viktorstrate** [comment] 2022-10-09 18:38
Yes `short Huffman data` means that the JPEG is corrupt

**Comment by IamSwap** [comment] 2022-11-25 07:18
Any updates on this?

**Comment by eerison** [comment] 2023-10-01 17:09
I do not have any file in /photos folder, But I am still getting this error 👀 

2023/10/01 17:07:55 Did not find auth-token cookie
2023/10/01 17:07:55 POST 200 localhost/api/graphql 2.655036ms unauthenticated

**Comment by eerison** [comment] 2023-10-01 17:48
> I do not have any file in /photos folder, But I am still getting this error 👀
> 
> 2023/10/01 17:07:55 Did not find auth-token cookie 2023/10/01 17:07:55 POST 200 localhost/api/graphql 2.655036ms unauthenticated

Ok it was other issue in my case, I am using traefik and when I was trying to access via proxy it does not work, when I access from docker's ports it worked, then I added the user/pass and folder path, and it works.

and I tested again from proxy after first login, and now it is also working via proxy 🤯

**Comment by kkovaletp** [comment] 2024-05-12 13:12
Linked the PR, which fixes the issue, closing it as completed

**Closed by kkovaletp** 2024-05-12 13:12 UTC
Labels: bug, scanner
