### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by UsefulVid** [photoview/photoview#944] opened 2024-05-11 17:26 UTC
**Describe the bug**
Container fails to start

**To Reproduce**
Start the docker container

**Expected behavior**
Container should start

**Screenshots**
![image](https://github.com/photoview/photoview/assets/39967070/c08fd088-3054-409c-add3-746d114ced5d)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? yes
 - Database not sure, is this not installed via docker?
 - Browser brave

**Additional context**
Just installed it on my synology with docker according to the readme.
Do I have to install the db additionally?

```


viktorstrate-photoview-1
date,stream,content
2024/05/11 19:16:13,stdout,	/app/server.go:45 +0x128

2024/05/11 19:16:13,stdout,main.main()

2024/05/11 19:16:13,stdout,	/app/database/database.go:177 +0x66

2024/05/11 19:16:13,stdout,github.com/photoview/photoview/api/database.MigrateDatabase(0xe5ab29?)

2024/05/11 19:16:13,stdout,	/go/pkg/mod/gorm.io/gorm@v1.23.7/gorm.go:395 +0x5e

2024/05/11 19:16:13,stdout,"gorm.io/gorm.(*DB).SetupJoinTable(0x3?, {0xdb2940, 0xc0002b7c70}, {0xe473c3, 0x6}, {0xd40d40, 0xc00020ab40})
"
2024/05/11 19:16:13,stdout,	/go/pkg/mod/gorm.io/gorm@v1.23.7/gorm.go:363 +0x18

2024/05/11 19:16:13,stdout,gorm.io/gorm.(*DB).getInstance(0x300000002?)

2024/05/11 19:16:13,stdout,goroutine 1 [running]:

2024/05/11 19:16:13,stdout,

2024/05/11 19:16:13,stdout,[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7d8678]

2024/05/11 19:16:13,stdout,panic: runtime error: invalid memory address or nil pointer dereference

2024/05/11 19:16:08,stdout,"2024/05/11 17:16:08 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
"
2024/05/11 19:16:03,stdout,"2024/05/11 17:16:03 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
"
2024/05/11 19:15:58,stdout,"2024/05/11 17:15:58 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
"
2024/05/11 19:15:53,stdout,"2024/05/11 17:15:53 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
"
2024/05/11 19:15:48,stdout,"2024/05/11 17:15:48 WARN: Could not ping database: Environment variable PHOTOVIEW_MYSQL_URL missing, exiting. Will retry after 5 seconds
"
2024/05/11 19:15:48,stdout,2024/05/11 17:15:48 No .env file found

2024/05/11 19:15:48,stdout,2024/05/11 17:15:48 Starting Photoview...

```

**Comment by kkovaletp** [comment] 2024-05-11 17:49
@UsefulVid, it looks like the Photoview container doesn't have access to the DB. I guess that this is one of many issues, existing in the current docker-compose config from the `master` branch. Please try the config from my PR #863, where I fixed many previously detected issues.
Please let me know if that helps or not.

**Comment by UsefulVid** [comment] 2024-05-13 09:19
![image](https://github.com/photoview/photoview/assets/39967070/47c8b3f0-36c2-43ae-8185-b0e19b615aec)
My Container Station is not happy with the github url. Which URL should I use?

**Comment by kkovaletp** [comment] 2024-05-13 10:08
@UsefulVid, you need to open that URL in your browser and read the changes in Readme file, then follow the instructions for the docker deployment and download the .env and docker-compose examples from this branch and edit them as described

**Comment by kkovaletp** [comment] 2024-06-04 13:25
@UsefulVid, any updates on this issue?
I hope that you've successfully reconfigured your setup according to the instructions from [https://github.com/photoview/photoview/tree/master#getting-started--setup-with-docker](https://github.com/photoview/photoview/tree/master#getting-started--setup-with-docker)

If not, let us know the details

**Comment by kkovaletp** [comment] 2024-06-28 07:44
We've released the new version recently with the new config examples and the configuration procedure in the Readme. Please try it and if the same issue is reproduced, please reopen this issue by adding more details about your setup (in particular, how is the DB container configured in the compose file and whether it has all needed variables from the `.env` (I don't need to see their values, just make sure that they are not empty and uncommented))

Until that closing it as not planned: it looks like it was caused by misconfiguration

**Closed by kkovaletp** 2024-06-28 07:44 UTC
Labels: bug, docker, pending response
