### ISSUE TITLE
Docker build of customized image failed to install GO dependencies

### ISSUE THREAD

**Issue by leunMar** [photoview/photoview#1030] opened 2024-08-31 10:01 UTC
**Describe the bug**
I tried to build the photoview docker image based on https://github.com/photoview/photoview/issues/503#issuecomment-913723664. It failed with a stream error from a go command, see below. I was not able to solve it on my own. Has someone seen this error? Any ideas?

**To Reproduce**
1. Edit docker compose file as in https://github.com/photoview/photoview/issues/503#issuecomment-913723664
2. Run `docker compose build`

**Expected behavior**
Build should finish without error.

**Logs**
```
 => ERROR [photoview api 6/8] RUN source /app/scripts/set_compiler_env.sh   && go env   && go   1715.1s
------                                                                                                  
> [photoview api 6/8] RUN source /app/scripts/set_compiler_env.sh   && go env   && go mod download   && sed -i 's/-march=native//g' /go/pkg/mod/github.com/!kagami/go-face*/face.go   && go install     github.com/mattn/go-sqlite3     github.com/Kagami/go-face:                                                     
1.733 GO111MODULE=''                                                                                    
1.733 GOARCH='arm64'                                                                                    
1.733 GOBIN=''
1.733 GOCACHE='/root/.cache/go-build'
1.733 GOENV='/root/.config/go/env'
1.733 GOEXE=''
1.733 GOEXPERIMENT=''
1.733 GOFLAGS=''
1.733 GOHOSTARCH='arm64'
1.733 GOHOSTOS='linux'
1.733 GOINSECURE=''
1.733 GOMODCACHE='/go/pkg/mod'
1.733 GONOPROXY=''
1.733 GONOSUMDB=''
1.733 GOOS='linux'
1.733 GOPATH='/go'
1.733 GOPRIVATE=''
1.733 GOPROXY='https://proxy.golang.org,direct'
1.733 GOROOT='/usr/local/go'
1.733 GOSUMDB='sum.golang.org'
1.733 GOTMPDIR=''
1.733 GOTOOLCHAIN='local'
1.733 GOTOOLDIR='/usr/local/go/pkg/tool/linux_arm64'
1.733 GOVCS=''
1.733 GOVERSION='go1.22.6'
1.733 GCCGO='gccgo'
1.733 AR='ar'
1.733 CC='aarch64-linux-gnu-gcc'
1.733 CXX='aarch64-linux-gnu-g++'
1.733 CGO_ENABLED='1'
1.733 GOMOD='/app/api/go.mod'
1.733 GOWORK=''
1.733 CGO_CFLAGS='-O2 -g'
1.733 CGO_CPPFLAGS=''
1.733 CGO_CXXFLAGS='-O2 -g'
1.733 CGO_FFLAGS='-O2 -g'
1.733 CGO_LDFLAGS='-O2 -g'
1.733 PKG_CONFIG='pkg-config'
1.734 GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3070969005=/tmp/go-build -gno-record-gcc-switches'
1714.7 go: github.com/h2non/filetype@v1.1.3: read "https://proxy.golang.org/github.com/h2non/filetype/@v/v1.1.3.zip": stream error: stream ID 11; INTERNAL_ERROR; received from peer
1714.7 go: golang.org/x/text@v0.17.0: read "https://proxy.golang.org/golang.org/x/text/@v/v0.17.0.zip": stream error: stream ID 7; INTERNAL_ERROR; received from peer
------
failed to solve: process "/bin/bash -euo pipefail -c source /app/scripts/set_compiler_env.sh   && go env   && go mod download   && sed -i 's/-march=native//g' ${GOPATH}/pkg/mod/github.com/!kagami/go-face*/face.go   && go install     github.com/mattn/go-sqlite3     github.com/Kagami/go-face" did not complete successfully: exit code: 1
```

**Your environment:**
 - arm64
 - ubuntu 22.04
 - Version: master bb66a8b

**Comment by kkovaletp** [comment] 2024-08-31 11:48
@googollee, do you have some thoughts on what might cause this error?

@leunMar, thanks for reporting the issue. As a workaround, you can build only the UI part of the image by providing the `--target ui` and needed `--build-arg` for the `UI_PUBLIC_URL` and `REACT_APP_API_ENDPOINT` variables. Finally, you can run it as a separate image in a similar way to the https://github.com/photoview/photoview?tab=readme-ov-file#start-ui-server-with-docker instructions. You'll need to modify them according to your use case.

**Comment by googollee** [comment] 2024-08-31 19:20
From the error, it looks like a failure to download the go library. Are you from China?

**Comment by leunMar** [comment] 2024-08-31 19:44
> From the error, it looks like a failure to download the go library. Are you from China?

Germany, Europe

**Comment by leunMar** [comment] 2024-08-31 20:03
When I try to access the locations from the log manually there is no problem.

**Comment by googollee** [comment] 2024-08-31 21:04
`stream error: stream ID 11; INTERNAL_ERROR; received from peer` indicates that it's a network problem. Looks like it recovers itself.

**Comment by kkovaletp** [comment] 2024-09-01 05:30
As this issue is caused by user's infrastructure (network), there is nothing to fix from our side, so I'm closing the ticket.

**Closed** 2024-09-06 10:35 UTC
Labels: wontfix, dependencies, docker, go
