### ISSUE TITLE
Date in timeline doesn't match date of photo

### ISSUE THREAD

**Issue by HStep20** [photoview/photoview#550] opened 2021-09-29 21:35 UTC
**Describe the bug**
The Date in the timeline seems to be a day behind the actual date of the photo. 

**To Reproduce**
Open the Timeline view with any number of images in the filesystem.

**Expected behavior**
The date on the timeline should match the date in the metadata

**Screenshots**
A few examples. You can see the album it resides in (date hierarchy) as well as the info of the file itself compared to the day shown on the timeline.
https://i.imgur.com/GpXfyTL.png
https://i.imgur.com/lZPDG3B.png
https://i.imgur.com/qEPaLtb.png

**Your environment:**
 - Using Docker on Unraid with mySQL container. Version 2.3.8 (428c4fdc)

**Comment by ouafnico** [comment] 2021-10-04 11:35
Hello
I got the same.
I tried to correct the timezone on the docker image, but even after an analyze the time is still incorrect.

On my side I got 2 hours added on photos compared to the original time.

Any way to force a rescan?

**Comment by ouafnico** [comment] 2021-10-05 11:42
It tried to remove all the data on docker, and reindex the files with a docker using the good timezone : the problem persists.

All my pictures got 2 hours more than the original exif info.

**Comment by viktorstrate** [comment] 2021-10-05 17:07
Duplicate of #306

**Closed by viktorstrate** 2021-10-05 17:07 UTC
Labels: bug
