### ISSUE TITLE
Compatible MP4 files reported as not a supported media

### ISSUE THREAD

**Issue by Flaxee** [photoview/photoview#697] opened 2022-05-21 13:40 UTC
**Describe the bug**
I have a bunch of old .MOV files that I've encoded into web-compatible .MP4 files (MP4 container, faststart/web optimized, H264, AAC), but Photoview logs say "File is not a supported media" when scanning the files.
I have disabled ffmpeg encoding by using the environment variable `PHOTOVIEW_DISABLE_VIDEO_ENCODING=1`.
If I enable ffmpeg encoding, the files are successfully scanned and processed. However, I don't know if it's encoding the files into a supported media file or if it's actually accepting the files as they are. Is there a way to check this?

**To Reproduce**
1. Encode a video file as a web-optimized MP4 file that should be compatible with Photoview
2. Disable ffmpeg encoding by setting the environment variable `PHOTOVIEW_DISABLE_VIDEO_ENCODING=1`
3. Run a scan
4. View the logs and see the errors

**Expected behavior**
The .MP4 video files should be supported and they should be seen on the timeline. Photoview shouldn't have to use ffmpeg to encode them.

**Photoview logs**
```
2022/05/21 13:27:21 Scanning directory: /users/test
2022/05/21 13:27:21 Queue waiting for lock
2022/05/21 13:27:21 Queue running: in_progress: 0, max_tasks: 3, queue_len: 1
2022/05/21 13:27:21 Queue starting job
2022/05/21 13:27:21 Queue waiting
2022/05/21 13:27:21 Starting job
2022/05/21 13:27:21 File is not a supported media /users/test/MVI_1259.mp4
2022/05/21 13:27:21 Job finished
```

**Mediainfo**
```
# mediainfo MVI_1259.mp4 
General
Complete name                            : MVI_1259.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 1.38 MiB
Duration                                 : 2 s 262 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 5 105 kb/s
Encoded date                             : UTC 2013-06-08 17:04:09
Tagged date                              : UTC 2013-06-08 17:04:09
com.apple.quicktime.rating.user          : 0.000000
major_brand                              : qt  
minor_version                            : 537331968
compatible_brands                        : qt  CAEP
com.apple.quicktime.make                 : Canon
com.apple.quicktime.model                : Canon EOS 650D
creation_time                            : 2013-06-08T17:04:09.000000Z
encoder                                  : Lavf58.45.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 2 s 240 ms
Bit rate                                 : 5 017 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.097
Stream size                              : 1.34 MiB (97%)
Language                                 : English
Encoded date                             : UTC 2013-06-08 17:04:09
Tagged date                              : UTC 2013-06-08 17:04:09
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 2 s 262 ms
Bit rate mode                            : Variable
Bit rate                                 : 124 kb/s
Maximum bit rate                         : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 34.3 KiB (2%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2013-06-08 17:04:09
Tagged date                              : UTC 2013-06-08 17:04:09
```

Videofile is web-optimized. Verified by the "moov" atom being located at the beginning of the file:
```
# ffmpeg -v trace -i MVI_1259.mp4 2>&1 | grep -e type:\'mdat\' -e type:\'moov\'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c169d4c1c0] type:'moov' parent:'root' sz: 3520 40 1443497
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c169d4c1c0] type:'mdat' parent:'root' sz: 1439937 3568 1443497
```

**Your environment:**
 - Are you using Docker? Yes, Docker version 20.10.15, build fd82621
 - Database: MariaDB 10.6
 - Browser: N/A
 - Version: Latest 2.3.12 ([0b9d04ef](https://github.com/photoview/photoview/commit/0b9d04eff2b6f896a70e8d081b6706dc4068f732))

**Additional context**
The videofiles are encoded using the following ffmpeg command: `ffmpeg -hwaccel qsv -i "input.mov" -y -loglevel info -movflags +faststart+use_metadata_tags -map_metadata 0 -vcodec h264_qsv -global_quality 21 -acodec aac "outpu..mp4"` 
I have also tried to encode the files using Handbrake with the `Web > Vimeo YouTube 720p30` profile, which should produce a pretty standard web-compatible MP4 videofile.

The videofile I've been testing with is available for download on Dropbox:
https://www.dropbox.com/s/uegn1s7vpgttr8b/MVI_1259.mp4?dl=0

**Comment by flo-at** [comment] 2022-07-27 02:47
I'm having the same problem. I only use Photoview for viewing photos/videos. Everything (photos and videos) are tagged, sorted and encoded before Photoview gets to see them so I disabled the ffmpeg transcoding.

This function will only return true for the `SupportedMimetypes` which do not include MP4/M4V files, even though they are potentially perfectly fine for browser playback: https://github.com/photoview/photoview/blob/master/api/scanner/media_type/media_type.go#L240 

I guess this is not easy to fix because there will be lots of MP4 files that are not compatible because of incompatible H.264 profile and so on. By just looking at the MIME-Type it's not possible to tell if the file will be good or not.

**Comment by secco04** [comment] 2023-08-25 03:59
I got similar problems wich i habe to dig for mir info..
I have old movs hat were converted by photoview.
The Web optimized mp4 is then not playable.

**Comment by kkovaletp** [comment] 2024-09-22 08:16
1st of all, here is the misunderstanding in the meaning of the `PHOTOVIEW_DISABLE_VIDEO_ENCODING` variable. In fact, it controls not the encoding, but the support of video files in general. When you set it to `1`, you actually disable the video support completely.

The other part of the issue is the request to give Photoview previously prepared media files and instruct it to use them 'as is' and not convert them at all. Currently, it is not supported by the product architecture. Also, I see a big risk in implementing this change, as users might convert their videos into not fully compatible formats, which will break the product later on playing the video step. The current implementation (as far as I see) is much safer: it converts all the source videos, so if some of them are already converted in the same format, the process will be fast and straightforward. But it ensures that the cached video is compatible with the embedded player and plays fine.

There is another issue #674, which covers the case when a user wants to get the original media and doesn't want to get even a high-res version of the converted media. However, in this case, the media has to be downloaded to the viewer's system as a file any played offline.

With this, I'm closing this issue as not planned.

**Closed** 2024-10-01 07:43 UTC
Labels: bug, help wanted, scanner, go
