### ISSUE TITLE
idea: 1 a fliter, 2 delete item

### ISSUE THREAD

**Issue by Ariczh** [photoview/photoview#710] opened 2022-07-05 07:56 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
1 Maybe we can get a fliter to choose display videos or images in album and timeline? this will make us find old items easily.
2 Everyone have some bad memories which we want to delete it quickly & easily. a delete button in every item's info can did it with a FAST speed.

**Describe alternatives you've considered**
1 find it by mouse wheel
2 rm -rf /*

**Additional context**
N/A

**Comment by viktorstrate** [comment] 2022-08-05 00:06
duplicate of #216

**Closed by viktorstrate** 2022-08-05 00:06 UTC
