### ISSUE TITLE
open /dev/core: permission denied

### ISSUE THREAD

**Issue by gaodoo** [photoview/photoview#915] opened 2024-02-21 10:59 UTC
### Discussed in https://github.com/photoview/photoview/discussions/667

<div type='discussions-op-text'>

<sup>Originally posted by **michael-keyes** March 28, 2022</sup>
Installed via docker-compose
Unable to scan or see any photos

Scanner error
IsPathMedia (/dev/core): get media type (/dev/core): could not open file to determine content-type /dev/core: open /dev/core: permission denied`</div>

**Comment by kkovaletp** [comment] 2024-02-21 19:53
Please try to reproduce the issue using the setup from #863 (reimplemented docker-compose environment, but original docker image) or #910 (in addition to the previous one, many other fixes merged and the config is developed to build the image locally from the source code).
If the issue is still reproducible, please provide more details about your environment and list all the changes, you made to the referenced setup.

**Comment by kkovaletp** [comment] 2024-06-04 13:32
@gaodoo, please try to reproduce the issue with the setup from the current `master` branch (according to the readme) and provide an update here. If not, I'm going to close the issue, as it doesn't contain enough info to let us understand and reproduce it on our side

**Comment by kkovaletp** [comment] 2024-08-02 09:39
No response from the issue reporter, also the issue looks invalid, so closing it as not planned

**Closed by kkovaletp** 2024-08-02 09:39 UTC
Labels: invalid, wontfix, needs information, pending response
