### ISSUE TITLE
Delete option with mark items and get a list to delete these on a separate script

### ISSUE THREAD

**Issue by terslowe** [photoview/photoview#1111] opened 2024-10-29 08:36 UTC
We really miss an option in the tool to delete items. I understand that adding a delete option could be risky, as it gives the tool the ability to remove items directly. However, what do you think about a feature that allows users to mark items for deletion using their full path? Then, we could export the marked items to a CSV file, like this:

`file1.jpg | /mnt/nfs/vacation/file1.jpg

file2.mov | /mnt/nfs/videos/file2.mov`

This would make the Photoview tool much more user-friendly, allowing us to mark items for deletion without creating any risk, and then handle the deletion ourselves using separate tools. A follow-up project could be to create a script or find a tool that can delete items based on entries in a CSV file.

I’m surprised this feature hasn’t been considered sooner!

**Comment by terslowe** [comment] 2024-10-29 08:50
I have checked also other requests like this, but this request should be a game changer if you can implement this.

Again, We know the tool is read-only and also nobody will this tool to make changes on the library.

It should be possible on the tool to only MARK items and see the marked items on a separate page (like favorite checkbox) so you can see which you have marked than you can copy these filenames and delete these itmes by another tool.

**Comment by kkovaletp** [comment] 2024-10-29 19:46
@terslowe, thanks for bringing this use case to the discussion!
1st of all, I'd like to confirm 1 thing, you've mentioned in your comments: Photoview is by design a read-only media gallery. This is not going to be changed.

> It should be possible on the tool to only MARK items and see the marked items on a separate page

This makes sense, and we already have an issue, requesting this functionality: #833. Please read (and feel free to comment) that issue, as well as other issues, mentioned there.
As far as I see, the tags implementation would allow to introduce the `#for_deletion` (or similar) tag, which you can use to mark media. Also, there should be a page to filter and view media, tagged by specific tags, so you can see that list in the UI. Having the tags, as additional metadata in the DB, it should be easy to write a script to extract a list of file paths for media with the corresponding tag.

With this, I'm closing this issue as a duplicate to the #833.

**Closed by kkovaletp** 2024-10-29 19:46 UTC
