### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by ALutz273** [photoview/photoview#575] opened 2021-10-20 07:02 UTC
**Describe the bug**
I would like to download an album and get an error

**To Reproduce**
GET 500 xxxxxxx:8000/api/download/album/7/original 3.044911489s user: admin
ERROR: Failed to copy file data, when downloading album (7): write tcp 172.21.0.3:8000->xxx.xxx.xxx.xxx:57421: write: broken pipe
http: superfluous response.WriteHeader call from github.com/gorilla/handlers.(*compressResponseWriter).WriteHeader (compress.go:26)

**Your environment:**
Feel free to remove and add what you think might be useful.

Docker version 19.03.15, build 99e3ed8919
mariadb:10.5
Firefox 93.0 Windows
2.3.8 (428c4fdc)

**Comment by kkovaletp** [comment] 2024-09-23 09:44
The “broken pipe” error typically occurs when one end of a TCP connection tries to write data to a connection that has already been closed by the other end.
Most probably, it was caused by an unstable network connection or some other environment-related issues.
As during these years nobody else commented this issue, I'm closing it as misconfiguration

**Closed by kkovaletp** 2024-09-23 09:44 UTC
Labels: bug
