### ISSUE TITLE
Doesn't work on Safari

### ISSUE THREAD

**Issue by numen31337** [photoview/photoview#464] opened 2021-07-30 07:57 UTC
**Describe the bug**
The empty placeholders are shown on the place of photos on both iOS Safari and macOS Safari.
It also works fine on macOS Chrome, but still doesn't work on iOS Chrome, which I understand indicates some WebKit issues.

**Screenshots**
![IMG_3560](https://user-images.githubusercontent.com/5677845/127619424-bb15b9b9-0e9a-4f00-8dc9-1eedd8180b92.PNG)
<img width="1494" alt="Screenshot 2021-07-30 at 09 45 15" src="https://user-images.githubusercontent.com/5677845/127619429-f602c5e1-0ebd-4ec5-b2c5-e01115b8f29a.png">
https://user-images.githubusercontent.com/5677845/127620752-ba3ebead-106c-428c-9315-91939d3f33de.mp4

**Your environment**
Both demo site and local docker deployment.

**Additional context**
This problem was observed by me about two months ago (and dismissed because of this issue) when I was checking out this project for my family library and just now on the demo site.

Unfortunately, I'm far away from web development so it doesn't look like I could be of any use here. It looks like something is just not triggering lazy loading of them. The icons appear on both macOS and iOS when you scroll all the way down the page (see the video attached).

**Comment by viktorstrate** [comment] 2021-07-30 08:07
I think this is a duplicate of #324

**Closed** 2021-07-30 08:07 UTC
Labels: bug
