### ISSUE TITLE
Disconnection on refresh

### ISSUE THREAD

**Issue by ouafnico** [photoview/photoview#558] opened 2021-10-06 08:28 UTC
**Describe the bug**
When browsing the website, I got some disconnection and got back to the authentication page.

**To Reproduce**
It's seems to happen when asking photoview some treatments. 
For exemple, analyzing folders, or merging some faces.

1. Log on photoview
2. Go to people
3. Choose and face and merge it with another
4. Refresh the page, you are disconnected!

or 
1. Log on photoview
2. Go to people
3. Clic to recognize unlabeled faces
4. Refresh the page, you are disconnected!

Technically I don't have to refresh manually the page, but when manipulating faces I got some blank pages (probably due to the load of server)

**Screenshots**
If I can record it I will post it.

**Your environment:**
Photoview 2.3.8 running on docker (host : Debian 11)

 - Are you using Docker? yes
 - Database : mariadb 10.5
 - Browser : brave
 - Version : 1.30.87 

If I can help/test anyway.

**Comment by ouafnico** [comment] 2021-11-02 07:59
It happens too when : 
- you go to settings
-ask for a rescan
- try to go to photos (you are disconnected)

**Comment by Rolf-Smit** [comment] 2022-02-17 00:02
Just found out about this photo manager/viewer, but this issue is already driving me nuts 😆 

I can also reproduce it whenever I merge a face, after clicking the merge button nothing happens, but if I then try to navigate to a different page, or refresh the page, my session gets invalidated.

**Comment by ouafnico** [comment] 2022-09-02 12:44
Hi team,

Any idea how to priorise this?

**Comment by kkovaletp** [comment] 2024-09-23 14:27
It looks like this issue is fixed by some recent changes. At least I cannot reproduce it and didn't see it for a long time. So, I'm closing it as completed. If you still affected by it, please reopen and share more info on how to reproduce

**Closed by kkovaletp** 2024-09-23 14:27 UTC
Labels: bug
