### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by winnipeg21** [photoview/photoview#781] opened 2022-12-07 04:07 UTC
**Describe the bug**
I do a file scan and after a few seconds it crashes and stops the scan

**To Reproduce**
1. Start a fresh install
2. Do a scan of over 5k photos

**Expected behavior**
Not to crash

**Screenshots**
Doesn't really apply here. Here's my [log ](https://pastebin.com/Q6LKQZD4)

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? [yes / no] Yes
 - Database [e.g. mariadb 10.5]  10.10.2 MariaDB
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 2.0.0] 2.3 (or whatever is latest)

**Additional context**
Seems it is a memory error (panic: runtime error: invalid memory address or nil pointer dereference), my server has 16gb of ram while scanning only 4gb is used system wide. CPU is an i5 6500

**Comment by trailfog** [comment] 2023-06-24 13:50
I also just encountered this crash. It is not actually caused by a photo, but rather by a video in your collection. The Server isn't running out of RAM, but ffmpeg is trying to read from an invalid location. Most likely, like in my case, the mp4 file was corrupted. Once removed, the scan successfully completed.

I managed to find the offending file by setting the `Scanner concurrent workers` setting to `1` and observing the last log line just before the crash. Then removed the file from the filesystem.

However, I think the crash of ffmpeg should be caught, handled and reported to the user, instead of just restarting the photoview server.

**Comment by charles-cai** [comment] 2023-07-16 10:10
My Unraid Photoview docker instance crashed with exactly the same error when scanning big photo/video library, with default 3 jobs. Since I changed to 1 job, it seems to be working on fine for hours without crashing around the same folder.

**Comment by kkovaletp** [comment] 2024-05-08 07:21
This issue must be partially fixed by the #892, but sure, correct error handling and checking the file for correctness before scanning it would be a good improvement (we have #939 for this part).
Closing it for now. If you think that something is still missing, feel free to open a new issue with a detailed description.

**Closed by kkovaletp** 2024-05-08 07:21 UTC
Labels: bug
